@startuml
actor User as user
participant "DMS 1\n(a.k.a. Service Provider)" as dms1 #53c68c
participant "DMS 2\n(a.k.a. Compute Provider 1)" as dms2 #3385ff
participant "DMS 3\n(a.k.a. Compute Provider 2)" as dms3 #ffa31a
participant "DMS 4\n(a.k.a. Compute Provider 3)" as dms4 #bfbfbf


  note right of dms1
    at this moment, dms1 has the following bids registered:
    for Job-1: bid21_msg & bid41_msg
    for Job-2: bid32_msg & bid42_msg
  end note

loop Generate deployment plan
  note right of dms1
    In order to ensure a valid deployment, we have to be able
    to reason about the network of nodes that we have selected
    (mostly their connetivity and capabilities)
    And for that we need to generate a subnetwork graph
    And represent it in a proper format / type
  end note
  dms1 -> dms2 : Actor.Send(returnConnectivityInfo(dms3))
  activate dms1 #53c68c
  activate dms2 #3385ff
  dms2 -> dms1 : connectivityInfo(dms2<->dms3)
  dms1 -> dms2 : Actor.Send(returnConnectivityInfo(dms4))
  dms2 -> dms1 : connectivityInfo(dms2<->dms4)
  deactivate dms2
  activate dms4 #bfbfbf
  dms1 -> dms4 : Actor.Send(returnConnectivityInfo(dms3))
  dms4 -> dms1 : connectivityInfo(dms4<->dms3)
  deactivate dms4
  activate dms3 #ffa31a
  dms1 -> dms3 : Actor.Send(returnConnectivityInfo(dms4))
  dms3 -> dms1 : connectivityInfo(dms3<->dms4)
  deactivate dms3
  dms1 --> dms1 : subnetworkGraph := {connectivityInfo(dms2<->dms3), \nconnectivityInfo(dms2<->dms4), \nconnectivityInfo(dms4<->dms3), \nconnectivityInfo(dms3<->dms4)}
  dms1 --> dms1 : deploymentPlan := dms1.Actor.GenerateDeploymentPlan(subnetworkGraph, [bid21, bid32, bid41, bid42])
  note right of dms1
    we have to implement logic of selecting best combination of bids
    considering how they compare to each other
    and our preferences and network configuration / requirements
  end note
    dms1 --> dms1 : deploymentPlan = [{Job-1: bid_21, Job-2: bid_42}, {Job-1: bid_21, Job-2: bid_32}...}
  note right of dms1
    In its simplest form
    deployment plan is just an orderd list of mapping
    of jobs to bids (i.e. machines)
  end note
  deactivate dms1
end



@enduml

'main under-developed aspects:
' job description format / type with connectivity semantics;
