@startuml
participant "DMS 1\n(a.k.a. Service Provider)" as dms1 #53c68c
participant "DMS 2\n(a.k.a. Compute Provider 1)" as dms2 #3385ff
participant "DMS 3\n(a.k.a. Compute Provider 2)" as dms3 #ffa31a
participant "DMS 4\n(a.k.a. Compute Provider 3)" as dms4 #bfbfbf

loop search and match
  dms1 --> dms1 : Actor.Publish(msg1)
  dms1 --> dms1 : Actor.Publish(msg2)
  note over dms1
    Settings:
    Publish job request to the whole network
    And wait for the {timeout} time
    
    Diagram below considers only subset of the network
    which eventually participates in the deployment
  end note
  deactivate dms1
  skinparam sequenceMessageAlign center
  loop broadcast reaches dms2
    group msg1
      dms1 -> dms2 : Actor.Receive(msg1)
      activate dms2 #3385ff
      group Execute behavior of msg1 (provide Bid for bid_request_1?)
        dms2 --> dms2 : Actor.availableHardwareCapability.Compare(bid_request_1.requestedHardwareCapability)\n--> Comparison: comparison21
        alt comparison21 == Better:
          dms2 --> dms2 : bid21_msg Envelope :=Actor.constructBid(bid_request_1)
          dms2 -> dms1 : Actor.Send(bid21_msg)
          deactivate dms2
          activate dms1 #53c68c
        end
      end
    end
    dms1 --> dms1 : register bid21_msg for bid_request_1 for future processing
    
    group msg2
      
      dms1 -> dms2 : Actor.Receive(msg2)
      deactivate dms1
      activate dms2 #3385ff
      group Execute behavior of msg2 (provide Bid for bid_request_2?)
        dms2 --> dms2 : Actor.availableHardwareCapability.Compare(bid_request_2.requestedHardwareCapability)\n--> Comparison: comparison22
        alt comparison22 == Worse:
          dms2 --> dms2 : do nothing / garbage collect
          deactivate dms2
        end
      end
    end
  end

  loop broadcast reaches dms3
    group msg1
      dms1 -> dms3 : Actor.Receive(msg1)
      activate dms3 #ffa31a
      group Execute behavior of msg1 (provide Bid for bid_request_1?)
        dms3 --> dms3 : Actor.availableHardwareCapability.Compare(bid_request_1.requestedHardwareCapability)\n--> Comparison: comparison31
        alt comparison31 == Worse:
          dms3 --> dms3 : do nothing / garbage collect
        end
      end
    end
    group msg2
      dms1 -> dms3 : Actor.Receive(msg2)
      group Execute behavior of msg2 (provide Bid for bid_request_2?)
        dms3 --> dms3 : Actor.availableHardwareCapability.Compare(bid_request_2.requestedHardwareCapability)\n--> Comparison: comparison32
        alt comparison32 == Better:
          dms3 --> dms3 : bid32_msg Envelope :=Actor.constructBid(bid_request_2)
          dms3 -> dms1 : Actor.Send(bid32_msg)
          deactivate dms3
          activate dms1 #53c68c
        end
      end
    end

    dms1 --> dms1 : register bid32_msg for bid_request_2 for future processing
  end

  loop broadcast reaches dms4
    group msg1
      dms1 -> dms4 : Actor.Receive(msg1)
      deactivate dms1
      activate dms4 #bfbfbf
      group Execute behavior of msg1 (provide Bid for bid_request_1?)
        dms4 --> dms4 : Actor.availableHardwareCapability.Compare(bid_request_1.requestedHardwareCapability)\n--> Comparison: comparison41
        alt comparison31 == Better:
          dms4 --> dms4 : bid41_msg Envelope :=Actor.constructBid(bid_request_1)
          dms4 -> dms1 : Actor.Send(bid41_msg)
          dms4 --> dms4 : (reserve capacity for the chosen timeout)
          deactivate dms4
          activate dms1 #53c68c
        end
      end
    end
    dms1 --> dms1 : register bid41_msg for bid_request_2 for future 
    
    group msg2
      dms1 -> dms4 : Actor.Receive(msg2)
      deactivate dms1
      activate dms4 #bfbfbf
      group Execute behavior of msg2 (provide Bid for bid_request_2?)
        dms4 --> dms4 : Actor.availableHardwareCapability.Compare(bid_request_2.requestedHardwareCapability)\n--> Comparison: comparison42
        alt comparison42 == Better:
          dms4 --> dms4 : bid42_msg Envelope :=Actor.constructBid(bid_request_2)
          dms4 -> dms1 : Actor.Send(bid42_msg)
          deactivate dms4
          activate dms1 #53c68c
        end
      end
    end
    dms1 --> dms1 : register bid42_msg for bid_request_2 for future processing
  end
  dms1 --> dms1 : SearchAndMatchingTimeout reached
  note right of dms1
    The logic of terminating the search and matching loop
    can depend on different factors
    e.g. we may have received bids from all nodes
    or we may have received bids from enough number of nodes
    or we may have received bids from all nodes with enough capacity
    or the timeout is reached, etc.
  end note
  deactivate dms1
end

@enduml

'main under-developed aspects:
' job description format / type with connectivity semantics;
