@startuml
actor User as user
participant "DMS 1\n(a.k.a. Service Provider)" as dms1 #53c68c
participant "DMS 2\n(a.k.a. Compute Provider 1)" as dms2 #3385ff
participant "DMS 3\n(a.k.a. Compute Provider 2)" as dms3 #ffa31a
participant "DMS 4\n(a.k.a. Compute Provider 3)" as dms4 #bfbfbf

  group Execution monitoring Job2
    note over dms1, Allocation21 
      monitor job execution as needed
    end note 

    Allocation21 -> dms1 : Send job status updates
    note over Allocation21, dms1
        Execution environment, telemetry, logging, heartbeats, 
        data access works correctly for the job to be finished;
    end note

    alt Job success
        Allocation21 -> dms1 : Message that the job is completed (with proof)
        Allocation21 -> dms2 : Message that the job is completed (with proof)
        note over dms2, Allocation21
          This is not yet defined as job verification logic is complex
          and may involve external varifiers, hopefully integrated from other projects
          from the ecosystem; for now lets assume that the the initiator of the job
          can verify its correctness, which is the base case;
        end note
    else Execution error
        note over Allocation21, dms1
          These messages will be done via supervisor model / strategy
          Following is a crude principle to be developed further
        end note
        Allocation21 -> dms1 : Error message
        Allocation21 -> dms2 : Error message
        note over dms1, dms2 : Carnage starts
    end
  end 




@enduml

'main under-developed aspects:
' job description format / type with connectivity semantics;
