@startuml
participant "DMS 1\n(a.k.a. Service Provider)" as dms1 #53c68c
participant "DMS 2\n(a.k.a. Compute Provider 1)" as dms2 #3385ff
participant "DMS 3\n(a.k.a. Compute Provider 2)" as dms3 #ffa31a
participant "DMS 4\n(a.k.a. Compute Provider 3)" as dms4 #bfbfbf

  group Invocation and allocation Job-1
    dms1 -> dms2 : Invocation for a job: actor.Actor.Send(behavior=invocation(job21)))
    dms2 --> Allocation21 ** : Create new Allocation as an actor via actor.Actor.New() and jobs.Allocation.NewAllocation() methods
    Allocation21 -> dms2 : Add new actor to Supervision tree / strategy;
    dms --> Allocation21 : start job execution

   end


@enduml

'main under-developed aspects:
' job description format / type with connectivity semantics;
