@startuml
skinparam participant {
    BackgroundColor LightBlue
    BorderColor DeepSkyBlue
}

skinparam sequence {
    ArrowColor DarkGreen
    ActorBorderColor DarkGreen
    LifeLineBorderColor DarkGreen
}

title Contract Settlement Sequence Diagram

actor Node1 as "dms.NodeID (n1)"
actor Node2 as "dms.NodeID (n2)"
actor DB as "Central Database"
actor JobsDB as "Jobs Database"

autonumber

Node1 -> DB: Retrieve Contract Details (contractID)
DB --> Node1: Return Contract Details

Node1 -> JobsDB: Fetch Job Results (contract.JobID)
JobsDB --> Node1: Return Job Results

Node1 -> JobsDB: Check Job Validation
DB --> Node1: Return Job Validation Result

note over Node1, Node2: Contract settlement initiated by Node1

Node1 -> DB: Check Contract Proof Exists
DB --> Node1: Confirm Contract Proof

Node1 -> Node2: Notify Contract Settlement
Node2 --> Node1: Acknowledge Notification

alt Job Verification Failed
    Node1 -> Node2: Notify Job Failed
    Node1 -> Node2: Proceed to Payment Back to Requestor
    Node2 --> Node1: Acknowledge Payment
else Job Successfully Executed with Proof
    Node1 -> Node2: Notify Job Success
   
     alt FixedJobPricing
        Contract -> Contract : calculatePaymentAmount (fixed price)
        Contract -> Node1 : full payment for fixed job
    end

    alt PeriodicPricing
        Contract -> Contract : calculatePaymentAmount for periodic pricing (based on usage)
        Contract -> Node1: payment based on job completion percentage
    end
    Node2 --> Node1: Acknowledge Payment
else Partial Success
    Node1 -> Node2: Notify Partial Success
    Node1 -> Node2: Proceed to Partial Payment to Both Parties
    Node2 --> Node1: Acknowledge Payment
end

note over Node1: Contract settlement process completed
Node1 -> DB: Update Contract Status
DB --> Node1: Acknowledge Status Update

note over Node1, DB: Contract status updated in the database
@enduml
