// Code generated by MockGen. DO NOT EDIT.
// Source: ./network/network.go
//
// Generated by this command:
//
//	mockgen -destination=./dms/node/geolocation/mock_network_test.go -source=./network/network.go -package=geolocation -exclude_interfaces=Messenger
//

// Package geolocation is a generated GoMock package.
package geolocation

import (
	context "context"
	net "net"
	reflect "reflect"
	time "time"

	peer "github.com/libp2p/go-libp2p/core/peer"
	config "gitlab.com/nunet/device-management-service/internal/config"
	crypto "gitlab.com/nunet/device-management-service/lib/crypto"
	network "gitlab.com/nunet/device-management-service/network"
	libp2p "gitlab.com/nunet/device-management-service/network/libp2p"
	common "gitlab.com/nunet/device-management-service/proto/generated/v1/common"
	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// AcceptSubnetPeer mocks base method.
func (m *MockNetwork) AcceptSubnetPeer(subnetID, peerID, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptSubnetPeer", subnetID, peerID, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptSubnetPeer indicates an expected call of AcceptSubnetPeer.
func (mr *MockNetworkMockRecorder) AcceptSubnetPeer(subnetID, peerID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptSubnetPeer", reflect.TypeOf((*MockNetwork)(nil).AcceptSubnetPeer), subnetID, peerID, ip)
}

// AddSubnetDNSRecords mocks base method.
func (m *MockNetwork) AddSubnetDNSRecords(subnetID string, records map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubnetDNSRecords", subnetID, records)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubnetDNSRecords indicates an expected call of AddSubnetDNSRecords.
func (mr *MockNetworkMockRecorder) AddSubnetDNSRecords(subnetID, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubnetDNSRecords", reflect.TypeOf((*MockNetwork)(nil).AddSubnetDNSRecords), subnetID, records)
}

// AddSubnetPeer mocks base method.
func (m *MockNetwork) AddSubnetPeer(subnetID, peerID, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubnetPeer", subnetID, peerID, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubnetPeer indicates an expected call of AddSubnetPeer.
func (mr *MockNetworkMockRecorder) AddSubnetPeer(subnetID, peerID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubnetPeer", reflect.TypeOf((*MockNetwork)(nil).AddSubnetPeer), subnetID, peerID, ip)
}

// Advertise mocks base method.
func (m *MockNetwork) Advertise(ctx context.Context, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Advertise", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Advertise indicates an expected call of Advertise.
func (mr *MockNetworkMockRecorder) Advertise(ctx, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advertise", reflect.TypeOf((*MockNetwork)(nil).Advertise), ctx, key, data)
}

// CreateSubnet mocks base method.
func (m *MockNetwork) CreateSubnet(ctx context.Context, subnetID string, routingTable map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", ctx, subnetID, routingTable)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockNetworkMockRecorder) CreateSubnet(ctx, subnetID, routingTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockNetwork)(nil).CreateSubnet), ctx, subnetID, routingTable)
}

// DestroySubnet mocks base method.
func (m *MockNetwork) DestroySubnet(subnetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySubnet", subnetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySubnet indicates an expected call of DestroySubnet.
func (mr *MockNetworkMockRecorder) DestroySubnet(subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySubnet", reflect.TypeOf((*MockNetwork)(nil).DestroySubnet), subnetID)
}

// GetBroadcastScore mocks base method.
func (m *MockNetwork) GetBroadcastScore() map[network.PeerID]*network.PeerScoreSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcastScore")
	ret0, _ := ret[0].(map[network.PeerID]*network.PeerScoreSnapshot)
	return ret0
}

// GetBroadcastScore indicates an expected call of GetBroadcastScore.
func (mr *MockNetworkMockRecorder) GetBroadcastScore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcastScore", reflect.TypeOf((*MockNetwork)(nil).GetBroadcastScore))
}

// GetHostID mocks base method.
func (m *MockNetwork) GetHostID() network.PeerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostID")
	ret0, _ := ret[0].(network.PeerID)
	return ret0
}

// GetHostID indicates an expected call of GetHostID.
func (mr *MockNetworkMockRecorder) GetHostID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostID", reflect.TypeOf((*MockNetwork)(nil).GetHostID))
}

// GetPeerIP mocks base method.
func (m *MockNetwork) GetPeerIP(p network.PeerID) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerIP", p)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPeerIP indicates an expected call of GetPeerIP.
func (mr *MockNetworkMockRecorder) GetPeerIP(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerIP", reflect.TypeOf((*MockNetwork)(nil).GetPeerIP), p)
}

// GetPeerPubKey mocks base method.
func (m *MockNetwork) GetPeerPubKey(peerID network.PeerID) crypto.PubKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerPubKey", peerID)
	ret0, _ := ret[0].(crypto.PubKey)
	return ret0
}

// GetPeerPubKey indicates an expected call of GetPeerPubKey.
func (mr *MockNetworkMockRecorder) GetPeerPubKey(peerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerPubKey", reflect.TypeOf((*MockNetwork)(nil).GetPeerPubKey), peerID)
}

// HandleMessage mocks base method.
func (m *MockNetwork) HandleMessage(messageType string, handler func([]byte, peer.ID)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessage", messageType, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockNetworkMockRecorder) HandleMessage(messageType, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockNetwork)(nil).HandleMessage), messageType, handler)
}

// HostPublicIP mocks base method.
func (m *MockNetwork) HostPublicIP() (net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HostPublicIP")
	ret0, _ := ret[0].(net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HostPublicIP indicates an expected call of HostPublicIP.
func (mr *MockNetworkMockRecorder) HostPublicIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostPublicIP", reflect.TypeOf((*MockNetwork)(nil).HostPublicIP))
}

// Init mocks base method.
func (m *MockNetwork) Init(arg0 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockNetworkMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockNetwork)(nil).Init), arg0)
}

// MapPort mocks base method.
func (m *MockNetwork) MapPort(subnetID, protocol, sourceIP, sourcePort, destIP, destPort string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapPort", subnetID, protocol, sourceIP, sourcePort, destIP, destPort)
	ret0, _ := ret[0].(error)
	return ret0
}

// MapPort indicates an expected call of MapPort.
func (mr *MockNetworkMockRecorder) MapPort(subnetID, protocol, sourceIP, sourcePort, destIP, destPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapPort", reflect.TypeOf((*MockNetwork)(nil).MapPort), subnetID, protocol, sourceIP, sourcePort, destIP, destPort)
}

// Notify mocks base method.
func (m *MockNetwork) Notify(ctx context.Context, preconnected func(network.PeerID, []network.ProtocolID, int), connected, disconnected func(network.PeerID), identified, updated func(network.PeerID, []network.ProtocolID)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, preconnected, connected, disconnected, identified, updated)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNetworkMockRecorder) Notify(ctx, preconnected, connected, disconnected, identified, updated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNetwork)(nil).Notify), ctx, preconnected, connected, disconnected, identified, updated)
}

// PeerConnected mocks base method.
func (m *MockNetwork) PeerConnected(p network.PeerID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeerConnected", p)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PeerConnected indicates an expected call of PeerConnected.
func (mr *MockNetworkMockRecorder) PeerConnected(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeerConnected", reflect.TypeOf((*MockNetwork)(nil).PeerConnected), p)
}

// Ping mocks base method.
func (m *MockNetwork) Ping(ctx context.Context, address string, timeout time.Duration) (types.PingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, address, timeout)
	ret0, _ := ret[0].(types.PingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockNetworkMockRecorder) Ping(ctx, address, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockNetwork)(nil).Ping), ctx, address, timeout)
}

// Publish mocks base method.
func (m *MockNetwork) Publish(ctx context.Context, topic string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNetworkMockRecorder) Publish(ctx, topic, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNetwork)(nil).Publish), ctx, topic, data)
}

// Query mocks base method.
func (m *MockNetwork) Query(ctx context.Context, key string) ([]*common.Advertisement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, key)
	ret0, _ := ret[0].([]*common.Advertisement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockNetworkMockRecorder) Query(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockNetwork)(nil).Query), ctx, key)
}

// RemoveSubnetDNSRecord mocks base method.
func (m *MockNetwork) RemoveSubnetDNSRecord(subnetID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubnetDNSRecord", subnetID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubnetDNSRecord indicates an expected call of RemoveSubnetDNSRecord.
func (mr *MockNetworkMockRecorder) RemoveSubnetDNSRecord(subnetID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubnetDNSRecord", reflect.TypeOf((*MockNetwork)(nil).RemoveSubnetDNSRecord), subnetID, name)
}

// RemoveSubnetPeer mocks base method.
func (m *MockNetwork) RemoveSubnetPeer(subnetID, peerID, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubnetPeer", subnetID, peerID, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubnetPeer indicates an expected call of RemoveSubnetPeer.
func (mr *MockNetworkMockRecorder) RemoveSubnetPeer(subnetID, peerID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubnetPeer", reflect.TypeOf((*MockNetwork)(nil).RemoveSubnetPeer), subnetID, peerID, ip)
}

// ResolveAddress mocks base method.
func (m *MockNetwork) ResolveAddress(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAddress", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAddress indicates an expected call of ResolveAddress.
func (mr *MockNetworkMockRecorder) ResolveAddress(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAddress", reflect.TypeOf((*MockNetwork)(nil).ResolveAddress), ctx, id)
}

// SendMessage mocks base method.
func (m *MockNetwork) SendMessage(ctx context.Context, hostID string, msg types.MessageEnvelope, expiry time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, hostID, msg, expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockNetworkMockRecorder) SendMessage(ctx, hostID, msg, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockNetwork)(nil).SendMessage), ctx, hostID, msg, expiry)
}

// SendMessageSync mocks base method.
func (m *MockNetwork) SendMessageSync(ctx context.Context, hostID string, msg types.MessageEnvelope, expiry time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageSync", ctx, hostID, msg, expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageSync indicates an expected call of SendMessageSync.
func (mr *MockNetworkMockRecorder) SendMessageSync(ctx, hostID, msg, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageSync", reflect.TypeOf((*MockNetwork)(nil).SendMessageSync), ctx, hostID, msg, expiry)
}

// SetBroadcastAppScore mocks base method.
func (m *MockNetwork) SetBroadcastAppScore(arg0 func(network.PeerID) float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBroadcastAppScore", arg0)
}

// SetBroadcastAppScore indicates an expected call of SetBroadcastAppScore.
func (mr *MockNetworkMockRecorder) SetBroadcastAppScore(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBroadcastAppScore", reflect.TypeOf((*MockNetwork)(nil).SetBroadcastAppScore), arg0)
}

// SetupBroadcastTopic mocks base method.
func (m *MockNetwork) SetupBroadcastTopic(topic string, setup func(*network.Topic) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupBroadcastTopic", topic, setup)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupBroadcastTopic indicates an expected call of SetupBroadcastTopic.
func (mr *MockNetworkMockRecorder) SetupBroadcastTopic(topic, setup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupBroadcastTopic", reflect.TypeOf((*MockNetwork)(nil).SetupBroadcastTopic), topic, setup)
}

// Start mocks base method.
func (m *MockNetwork) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockNetworkMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNetwork)(nil).Start))
}

// Stat mocks base method.
func (m *MockNetwork) Stat() types.NetworkStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(types.NetworkStats)
	return ret0
}

// Stat indicates an expected call of Stat.
func (mr *MockNetworkMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockNetwork)(nil).Stat))
}

// Stop mocks base method.
func (m *MockNetwork) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockNetworkMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockNetwork)(nil).Stop))
}

// Subscribe mocks base method.
func (m *MockNetwork) Subscribe(ctx context.Context, topic string, handler func([]byte), validator libp2p.Validator) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topic, handler, validator)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNetworkMockRecorder) Subscribe(ctx, topic, handler, validator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNetwork)(nil).Subscribe), ctx, topic, handler, validator)
}

// Unadvertise mocks base method.
func (m *MockNetwork) Unadvertise(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unadvertise", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unadvertise indicates an expected call of Unadvertise.
func (mr *MockNetworkMockRecorder) Unadvertise(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unadvertise", reflect.TypeOf((*MockNetwork)(nil).Unadvertise), ctx, key)
}

// UnmapPort mocks base method.
func (m *MockNetwork) UnmapPort(subnetID, protocol, sourceIP, sourcePort, destIP, destPort string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmapPort", subnetID, protocol, sourceIP, sourcePort, destIP, destPort)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmapPort indicates an expected call of UnmapPort.
func (mr *MockNetworkMockRecorder) UnmapPort(subnetID, protocol, sourceIP, sourcePort, destIP, destPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmapPort", reflect.TypeOf((*MockNetwork)(nil).UnmapPort), subnetID, protocol, sourceIP, sourcePort, destIP, destPort)
}

// UnregisterMessageHandler mocks base method.
func (m *MockNetwork) UnregisterMessageHandler(messageType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterMessageHandler", messageType)
}

// UnregisterMessageHandler indicates an expected call of UnregisterMessageHandler.
func (mr *MockNetworkMockRecorder) UnregisterMessageHandler(messageType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterMessageHandler", reflect.TypeOf((*MockNetwork)(nil).UnregisterMessageHandler), messageType)
}

// Unsubscribe mocks base method.
func (m *MockNetwork) Unsubscribe(topic string, subID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", topic, subID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockNetworkMockRecorder) Unsubscribe(topic, subID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockNetwork)(nil).Unsubscribe), topic, subID)
}
