// Code generated by MockGen. DO NOT EDIT.
// Source: ./types/types.go
//
// Generated by this command:
//
//	mockgen -destination=./dms/node/geolocation/mock_geoip_locator_test.go -source=./types/types.go -package=geolocation
//

// Package geolocation is a generated GoMock package.
package geolocation

import (
	net "net"
	reflect "reflect"

	geoip2 "github.com/oschwald/geoip2-golang"
	gomock "go.uber.org/mock/gomock"
)

// MockGeoIPLocator is a mock of GeoIPLocator interface.
type MockGeoIPLocator struct {
	ctrl     *gomock.Controller
	recorder *MockGeoIPLocatorMockRecorder
}

// MockGeoIPLocatorMockRecorder is the mock recorder for MockGeoIPLocator.
type MockGeoIPLocatorMockRecorder struct {
	mock *MockGeoIPLocator
}

// NewMockGeoIPLocator creates a new mock instance.
func NewMockGeoIPLocator(ctrl *gomock.Controller) *MockGeoIPLocator {
	mock := &MockGeoIPLocator{ctrl: ctrl}
	mock.recorder = &MockGeoIPLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoIPLocator) EXPECT() *MockGeoIPLocatorMockRecorder {
	return m.recorder
}

// City mocks base method.
func (m *MockGeoIPLocator) City(ipAddress net.IP) (*geoip2.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "City", ipAddress)
	ret0, _ := ret[0].(*geoip2.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// City indicates an expected call of City.
func (mr *MockGeoIPLocatorMockRecorder) City(ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "City", reflect.TypeOf((*MockGeoIPLocator)(nil).City), ipAddress)
}

// Country mocks base method.
func (m *MockGeoIPLocator) Country(ipAddress net.IP) (*geoip2.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Country", ipAddress)
	ret0, _ := ret[0].(*geoip2.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Country indicates an expected call of Country.
func (mr *MockGeoIPLocatorMockRecorder) Country(ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Country", reflect.TypeOf((*MockGeoIPLocator)(nil).Country), ipAddress)
}
