// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://nunet.io/tos",
        "contact": {
            "name": "Support",
            "url": "https://devexchange.nunet.io/",
            "email": "support@nunet.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device/status": {
            "get": {
                "description": "Retrieve device status whether paused/offline (unable to receive job deployments) or online",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Retrieve device status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Change device status to online (able to receive jobs) or offline (unable to receive jobs).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Change device status between online/offline",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dht": {
            "get": {
                "description": "Returns entire DHT content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Return a dump of the dht",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/onboarding/address/new": {
            "get": {
                "description": "Create a payment address from public key. Return payment address and private key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Create a new payment address.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.BlockchainAddressPrivKey"
                        }
                    }
                }
            }
        },
        "/onboarding/metadata": {
            "get": {
                "description": "Responds with metadata of current provideer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Get current device info.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Metadata"
                        }
                    }
                }
            }
        },
        "/onboarding/offboard": {
            "post": {
                "description": "Offboard runs offboarding process to remove the machine from the NuNet network.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Runs the offboarding process.",
                "responses": {
                    "200": {
                        "description": "device successfully offboarded",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/onboarding/onboard": {
            "post": {
                "description": "Onboard runs onboarding script given the amount of resources to onboard.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Runs the onboarding process.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Metadata"
                        }
                    }
                }
            }
        },
        "/onboarding/provisioned": {
            "get": {
                "description": "Get total memory capacity in MB and CPU capacity in MHz.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Returns provisioned capacity on host.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Provisioned"
                        }
                    }
                }
            }
        },
        "/onboarding/resource-config": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "changes the amount of resources of onboarded device .",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Metadata"
                        }
                    }
                }
            }
        },
        "/onboarding/status": {
            "get": {
                "description": "Returns json with 5 parameters: onboarded, error, machine_uuid, metadata_path, database_path.\n` + "`" + `onboarded` + "`" + ` is true if the device is onboarded, false otherwise.\n` + "`" + `error` + "`" + ` is the error message if any related to onboarding status check\n` + "`" + `machine_uuid` + "`" + ` is the UUID of the machine\n` + "`" + `metadata_path` + "`" + ` is the path to metadataV2.json only if it exists\n` + "`" + `database_path` + "`" + ` is the path to nunet.db only if it exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Onboarding status and other metadata.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.OnboardingStatus"
                        }
                    }
                }
            }
        },
        "/peers": {
            "get": {
                "description": "Gets a list of peers the libp2p node can see within the network and return a list of peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Return list of peers currently connected to",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/chat": {
            "get": {
                "description": "Get a list of chat requests from peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "List chat requests",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/chat/clear": {
            "get": {
                "description": "Clear chat request streams from peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Clear chat requests",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/chat/join": {
            "get": {
                "description": "Join a chat session started by a peer",
                "tags": [
                    "chat"
                ],
                "summary": "Join chat with a peer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/chat/start": {
            "get": {
                "description": "Start chat session with a peer",
                "tags": [
                    "chat"
                ],
                "summary": "Start chat with a peer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/depreq": {
            "get": {
                "description": "Set peer as the default receipient of deployment requests by setting the peerID parameter on GET request.\nShow peer set as default deployment request receiver by sending a GET request without any parameters.\nRemove default deployment request receiver by sending a GET request with peerID parameter set to '0'.",
                "tags": [
                    "peers"
                ],
                "summary": "Manage default deplyment request receiver peer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/dht": {
            "get": {
                "description": "Gets a list of peers the libp2p node has received a dht update from",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Return list of peers which have sent a dht update",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/file": {
            "get": {
                "description": "Get a list of file transfer requests from peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "List file transfer requests",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/file/accept": {
            "get": {
                "description": "Accept an incoming file transfer. Incoming file transfer stream ID is a required parameter.",
                "tags": [
                    "file"
                ],
                "summary": "Accept incoming file transfer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/file/clear": {
            "get": {
                "description": "Clear file transfer request streams from peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Clear file transfer requests",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/file/send": {
            "get": {
                "description": "Initiate file transfer to a peer. filePath and peerID are required arguments.",
                "tags": [
                    "file"
                ],
                "summary": "Send a file to a peer",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/peers/kad-dht": {
            "get": {
                "description": "Gets a list of peers the libp2p node has received a dht update from",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Return list of peers which have sent a dht update",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/self": {
            "get": {
                "description": "Gets self peer info of libp2p node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Return self peer info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/ws": {
            "get": {
                "description": "Sends a command to specific node and prints back response.",
                "tags": [
                    "peers"
                ],
                "summary": "Sends a command to specific node and prints back response.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/run/checkpoints": {
            "get": {
                "description": "ListCheckpointHandler scans data_dir/received_checkpoints and lists all the tar.gz files which can be used to resume a job. Returns a list of objects with absolute path and last modified date.",
                "tags": [
                    "run"
                ],
                "summary": "Returns a list of absolute path to checkpoint files.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.checkpoint"
                            }
                        }
                    }
                }
            }
        },
        "/run/deploy": {
            "get": {
                "description": "Loads deployment request from the DB after a successful blockchain transaction has been made and passes it to compute provider.",
                "tags": [
                    "run"
                ],
                "summary": "Websocket endpoint responsible for sending deployment request and receiving deployment response.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/telemetry/free": {
            "get": {
                "description": "Checks and returns the amount of free resources available",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Returns the amount of free resources available",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Get list of TxHashes along with the date and time of jobs done.",
                "tags": [
                    "run"
                ],
                "summary": "Get list of TxHashes for jobs done.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/utils.TxHashResp"
                            }
                        }
                    }
                }
            }
        },
        "/transactions/request-reward": {
            "post": {
                "description": "HandleRequestReward takes request from the compute provider, talks with Oracle and releases tokens if conditions are met.",
                "tags": [
                    "run"
                ],
                "summary": "Get NTX tokens for work done.",
                "parameters": [
                    {
                        "description": "Claim Reward Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.ClaimCardanoTokenBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.rewardRespToCPD"
                        }
                    }
                }
            }
        },
        "/transactions/send-status": {
            "post": {
                "description": "HandleSendStatus is used by webapps to send status of blockchain activities. Such token withdrawl.",
                "tags": [
                    "run"
                ],
                "summary": "Sends blockchain status of contract creation.",
                "parameters": [
                    {
                        "description": "Blockchain Transaction Status Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BlockchainTxStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions/update-status": {
            "post": {
                "description": "HandleUpdateStatus is used by webapps to update status of saved transactions with fetching info from blockchain using koios REST API.",
                "tags": [
                    "tx"
                ],
                "summary": "Updates blockchain transaction status of DB.",
                "parameters": [
                    {
                        "description": "Transaction Status Update Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.UpdateTxStatusBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vm/start-custom": {
            "post": {
                "description": "This endpoint is an abstraction of all primitive endpoints. When invokend, it calls all primitive endpoints in a sequence.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vm"
                ],
                "summary": "Start a VM with custom configuration.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/vm/start-default": {
            "post": {
                "description": "Everything except kernel files and filesystem file will be set by DMS itself.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vm"
                ],
                "summary": "Start a VM with default configuration.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.checkpoint": {
            "type": "object",
            "properties": {
                "checkpoint_dir": {
                    "type": "string"
                },
                "filename_path": {
                    "type": "string"
                },
                "last_modified": {
                    "type": "integer"
                }
            }
        },
        "types.BlockchainAddressPrivKey": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "mnemonic": {
                    "type": "string"
                },
                "private_key": {
                    "type": "string"
                }
            }
        },
        "types.BlockchainTxStatus": {
            "type": "object",
            "properties": {
                "transaction_status": {
                    "type": "string"
                },
                "transaction_type": {
                    "description": "No need of this param maybe be deprecated in future",
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "types.Gpu": {
            "type": "object",
            "properties": {
                "free_vram": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "tot_vram": {
                    "type": "integer"
                }
            }
        },
        "types.Metadata": {
            "type": "object",
            "properties": {
                "allow_cardano": {
                    "type": "boolean"
                },
                "available": {
                    "type": "object",
                    "properties": {
                        "cpu": {
                            "type": "integer"
                        },
                        "memory": {
                            "type": "integer"
                        }
                    }
                },
                "dashboard": {
                    "type": "string"
                },
                "gpu_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Gpu"
                    }
                },
                "name": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "ntx_price": {
                    "type": "number"
                },
                "public_key": {
                    "type": "string"
                },
                "reserved": {
                    "type": "object",
                    "properties": {
                        "cpu": {
                            "type": "integer"
                        },
                        "memory": {
                            "type": "integer"
                        }
                    }
                },
                "resource": {
                    "type": "object",
                    "properties": {
                        "cpu_max": {
                            "type": "integer"
                        },
                        "memory_max": {
                            "type": "integer"
                        },
                        "total_core": {
                            "type": "integer"
                        }
                    }
                },
                "update_timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.OnboardingStatus": {
            "type": "object",
            "properties": {
                "database_path": {
                    "type": "string"
                },
                "error": {},
                "machine_uuid": {
                    "type": "string"
                },
                "metadata_path": {
                    "type": "string"
                },
                "onboarded": {
                    "type": "boolean"
                }
            }
        },
        "types.Provisioned": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "number"
                },
                "memory": {
                    "type": "integer"
                },
                "total_cores": {
                    "type": "integer"
                }
            }
        },
        "utils.ClaimCardanoTokenBody": {
            "type": "object",
            "properties": {
                "compute_provider_address": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "utils.TxHashResp": {
            "type": "object",
            "properties": {
                "date_time": {
                    "type": "string"
                },
                "transaction_type": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "utils.UpdateTxStatusBody": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "utils.rewardRespToCPD": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "compute_provider_addr": {
                    "type": "string"
                },
                "datum": {
                    "type": "string"
                },
                "message_hash_action": {
                    "type": "string"
                },
                "message_hash_datum": {
                    "type": "string"
                },
                "reward_type": {
                    "type": "string"
                },
                "service_provider_addr": {
                    "type": "string"
                },
                "signature_action": {
                    "type": "string"
                },
                "signature_datum": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.4.169",
	Host:             "localhost:9999",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Device Management Service",
	Description:      "A dashboard application for computing providers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
