version: "1"
jobs:
  job1:
    type: ""
    metadata:
      namespace: ""
    locality: ["us"]
    volumes:
      volume1:
        type: output
        remote:
          type: ipfs
          endpoint: "123"
    children:
      job2:
        instances: 2
        execution:
          type: docker
          image: "alpine"
          environment:
            - ENV1: "value"
          command: "echo task 1"
        libraries:
          - pytorch:v1
        resources:
          cpu:
            arch: "x86"
            freq: 10000
            cores: 2
          memory:
            speed: 10000
            size: 10000
          gpus:
            - vendor: "nvidia"
              memory: 10000
        volumes:
          volume1:
            mountpoint: /
          volume2:
            type: imput
            remote:
              type: s3
              bucket: "bucket1"
            mountpoint: "/"
        networks:
          net1:
            type: subnet
            ports:
              - 8000
              - 9000
      job3:
        instances: 1
        execution:
          type: firecracker
          kernel_path: "./vmlinuz.bin"
          rootfs: "./root.img"
        resources:
        volumes:
          volume1:
            mountpoint: /
        networks:
  Job2:
    execution:
      type: docker
      image: "alpine"
      environment:
        - ENV1: "value"
      command: "echo task 1"

links:
  - type: job
    source: job1
    target: job1
    dependency: machine


