variables: 
  # https://hub.docker.com/r/alpine/git/tags
  GIT_VERSION: v2.30.1
  BUILD_DISABLED: "yes"
  DMS_BUILDER_VERSION: "0.5"
  # CODE_QUALITY_DISABLED: true
  # SKIP_UNIT_TESTS: true
  # DEFECTDOJO_DISABLED: true
  # CONTAINER_SCANNIG_DISABLED: true
  # SAST_DISABLED: true
  # SECRET_DETECTION_DISABLED: true
  # SEMVER_DISABLED: true
  # SONARQUBE_DISABLED: true
  # FEATURE_ENVIRONMENT_DISABLED: true

include:
  project: nunet/test-suite
  file: cicd/Auto-DevOps.gitlab-ci.yml
  ref: develop

image: registry.gitlab.com/nunet/device-management-service/nunet-dms-builder:0.4

Build:
  stage: build
  script:
    - echo "Building debian archives..."
    - bash maint-scripts/build.sh
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if:  $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(develop|staging|main)$/
    - if:  $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^(develop|staging|main)$/
      when: manual
    - when: never


Build DMS Builder:
  stage: build
  image:
     'docker:20.10.12-dind'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -f maint-scripts/Dockerfile.builder -t ${CI_REGISTRY_IMAGE}/nunet-dms-builder:${DMS_BUILDER_VERSION}
    - docker push ${CI_REGISTRY_IMAGE}/nunet-dms-builder:${DMS_BUILDER_VERSION}
  rules:
    - changes: 
        - maint-scripts/Dockerfile.builder
      if: $CI_COMMIT_BRANCH == "develop"

Deploy DMS:
  stage: deploy
  variables:
    CI_PARENT_PROJECT: dms
  trigger:
    forward:
      yaml_variables: true
      pipeline_variables: true
    project: nunet/nunet-infra
    branch: develop
  only:
    refs:
      - $CI_DEFAULT_BRANCH

.git:push:
  after_script:
    - cd "${CI_COMMIT_SHA}"

    - git checkout -B ${CI_COMMIT_BRANCH}
    
    - git add .
    
    - |-
      CHANGES=$(git status --porcelain | wc -l)

      if [ "$CHANGES" -gt "0" ]; then
        git status

        git commit -m "${COMMIT_MESSAGE}"

        git push -f origin "${CI_COMMIT_BRANCH}"  
      
      fi

  before_script:
    - git clone "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/nunet/open-api/device-management-api-spec" "${CI_COMMIT_SHA}"

    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

  image:
    entrypoint: ['']
    name: alpine/git:${GIT_VERSION}

deploy:openapi:
  extends: .git:push
  stage: .pre
  script:
    - mv api/docs/swagger.json "${CI_COMMIT_SHA}"
    - mv api/docs/device-management-api-spec.yaml "${CI_COMMIT_SHA}"
  only:
    refs:
      - $CI_DEFAULT_BRANCH
      - main
      - staging


Deploy:
  stage: deploy
  variables:
     ANSIBLE_HOST_KEY_CHECKING: "false"
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client python3-apt -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - pip install ansible ansible-lint jmespath docker
    - ansible-galaxy role install geerlingguy.docker geerlingguy.pip
  image: python:3
  script: 
    - ansible --version
    - DMS_VERSION=$(cat main.go | grep @version | awk {'print $3'})
    - ansible-playbook -i $ANSIBLE_INVENTORY -e dms_version=$DMS_VERSION maint-scripts/deploy/playbook.yaml 
  rules:
    - when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging"
