version: "2"
linters:
  default: none
  enable:
    - errcheck
    # - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
        - staticcheck
        text: "QF1008:"
      # exculude `types` and `utils` packages from revive's var-naming rule
      - path: (types|utils)
        linters:
          - revive
        text: "var-naming: avoid meaningless package names"


formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
