// Code generated by MockGen. DO NOT EDIT.
// Source: db/repositories/generic_entity_repository.go
//
// Generated by this command:
//
//	mockgen -source=db/repositories/generic_entity_repository.go -destination=dms/onboarding/mock_generic_entity_repository_test.go -package=onboarding
//

// Package onboarding is a generated GoMock package.
package onboarding

import (
	context "context"
	reflect "reflect"

	repositories "gitlab.com/nunet/device-management-service/db/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockGenericEntityRepository is a mock of GenericEntityRepository interface.
type MockGenericEntityRepository[T repositories.ModelType] struct {
	ctrl     *gomock.Controller
	recorder *MockGenericEntityRepositoryMockRecorder[T]
}

// MockGenericEntityRepositoryMockRecorder is the mock recorder for MockGenericEntityRepository.
type MockGenericEntityRepositoryMockRecorder[T repositories.ModelType] struct {
	mock *MockGenericEntityRepository[T]
}

// NewMockGenericEntityRepository creates a new mock instance.
func NewMockGenericEntityRepository[T repositories.ModelType](ctrl *gomock.Controller) *MockGenericEntityRepository[T] {
	mock := &MockGenericEntityRepository[T]{ctrl: ctrl}
	mock.recorder = &MockGenericEntityRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericEntityRepository[T]) EXPECT() *MockGenericEntityRepositoryMockRecorder[T] {
	return m.recorder
}

// Clear mocks base method.
func (m *MockGenericEntityRepository[T]) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockGenericEntityRepositoryMockRecorder[T]) Clear(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockGenericEntityRepository[T])(nil).Clear), ctx)
}

// Get mocks base method.
func (m *MockGenericEntityRepository[T]) Get(ctx context.Context) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGenericEntityRepositoryMockRecorder[T]) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGenericEntityRepository[T])(nil).Get), ctx)
}

// GetQuery mocks base method.
func (m *MockGenericEntityRepository[T]) GetQuery() repositories.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery")
	ret0, _ := ret[0].(repositories.Query[T])
	return ret0
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockGenericEntityRepositoryMockRecorder[T]) GetQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockGenericEntityRepository[T])(nil).GetQuery))
}

// History mocks base method.
func (m *MockGenericEntityRepository[T]) History(ctx context.Context, qiery repositories.Query[T]) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, qiery)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockGenericEntityRepositoryMockRecorder[T]) History(ctx, qiery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockGenericEntityRepository[T])(nil).History), ctx, qiery)
}

// Save mocks base method.
func (m *MockGenericEntityRepository[T]) Save(ctx context.Context, data T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockGenericEntityRepositoryMockRecorder[T]) Save(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGenericEntityRepository[T])(nil).Save), ctx, data)
}
