// Code generated by MockGen. DO NOT EDIT.
// Source: ../../types/resources.go
//
// Generated by this command:
//
//	mockgen -destination=mock_resource_manager_test.go -source=../../types/resources.go -package=onboarding -exclude_interfaces=UsageMonitor,ResourceOps
//

// Package onboarding is a generated GoMock package.
package onboarding

import (
	context "context"
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceManager is a mock of ResourceManager interface.
type MockResourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockResourceManagerMockRecorder
}

// MockResourceManagerMockRecorder is the mock recorder for MockResourceManager.
type MockResourceManagerMockRecorder struct {
	mock *MockResourceManager
}

// NewMockResourceManager creates a new mock instance.
func NewMockResourceManager(ctrl *gomock.Controller) *MockResourceManager {
	mock := &MockResourceManager{ctrl: ctrl}
	mock.recorder = &MockResourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceManager) EXPECT() *MockResourceManagerMockRecorder {
	return m.recorder
}

// AllocateResources mocks base method.
func (m *MockResourceManager) AllocateResources(arg0 context.Context, arg1 types.ResourceAllocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateResources", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AllocateResources indicates an expected call of AllocateResources.
func (mr *MockResourceManagerMockRecorder) AllocateResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateResources", reflect.TypeOf((*MockResourceManager)(nil).AllocateResources), arg0, arg1)
}

// CommitResources mocks base method.
func (m *MockResourceManager) CommitResources(arg0 context.Context, arg1 types.CommittedResources) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitResources", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitResources indicates an expected call of CommitResources.
func (mr *MockResourceManagerMockRecorder) CommitResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitResources", reflect.TypeOf((*MockResourceManager)(nil).CommitResources), arg0, arg1)
}

// DeallocateResources mocks base method.
func (m *MockResourceManager) DeallocateResources(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeallocateResources", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeallocateResources indicates an expected call of DeallocateResources.
func (mr *MockResourceManagerMockRecorder) DeallocateResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeallocateResources", reflect.TypeOf((*MockResourceManager)(nil).DeallocateResources), arg0, arg1)
}

// GetFreeResources mocks base method.
func (m *MockResourceManager) GetFreeResources(ctx context.Context) (types.FreeResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeResources", ctx)
	ret0, _ := ret[0].(types.FreeResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeResources indicates an expected call of GetFreeResources.
func (mr *MockResourceManagerMockRecorder) GetFreeResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeResources", reflect.TypeOf((*MockResourceManager)(nil).GetFreeResources), ctx)
}

// GetOnboardedResources mocks base method.
func (m *MockResourceManager) GetOnboardedResources(arg0 context.Context) (types.OnboardedResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnboardedResources", arg0)
	ret0, _ := ret[0].(types.OnboardedResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnboardedResources indicates an expected call of GetOnboardedResources.
func (mr *MockResourceManagerMockRecorder) GetOnboardedResources(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnboardedResources", reflect.TypeOf((*MockResourceManager)(nil).GetOnboardedResources), arg0)
}

// GetTotalAllocation mocks base method.
func (m *MockResourceManager) GetTotalAllocation() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAllocation")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAllocation indicates an expected call of GetTotalAllocation.
func (mr *MockResourceManagerMockRecorder) GetTotalAllocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAllocation", reflect.TypeOf((*MockResourceManager)(nil).GetTotalAllocation))
}

// UnCommittedResources mocks base method.
func (m *MockResourceManager) UnCommittedResources(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnCommittedResources", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnCommittedResources indicates an expected call of UnCommittedResources.
func (mr *MockResourceManagerMockRecorder) UnCommittedResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnCommittedResources", reflect.TypeOf((*MockResourceManager)(nil).UnCommittedResources), arg0, arg1)
}

// UpdateOnboardedResources mocks base method.
func (m *MockResourceManager) UpdateOnboardedResources(arg0 context.Context, arg1 types.Resources) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnboardedResources", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnboardedResources indicates an expected call of UpdateOnboardedResources.
func (mr *MockResourceManagerMockRecorder) UpdateOnboardedResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnboardedResources", reflect.TypeOf((*MockResourceManager)(nil).UpdateOnboardedResources), arg0, arg1)
}
