 ' START PREAMBLE

!$rootUrlLocal = ".."
!$rootUrlGitlab = "https://gitlab.com/nunet/device-management-service/-/raw/develop"

' package relative path: change this for each package
!$packageRelativePath = "/cmd"

!$packageUrlGitlab = $rootUrlGitlab + $packageRelativePath

' uncomment the following line to render all locally
' !$rootUrl = $rootUrlLocal
' uncomment the following line to render all from gitlab
!$rootUrl = $packageUrlGitlab

' END PREAMBLE

' START DIAGRAM

    interface cmd.GPU {
        -name() string
        -utilizationRate() uint32
        -memory() memoryInfo
        -temperature() float64
        -powerUsage() uint32
    }

    class cmd.ContainerOptions {
        +UseGPUs bool
        +Devices []string
        +Groups []string
        +Image string
        +Command []string
        +Entrypoint []string
    }

    class cmd.amdGPU {
        -index int
        -name() string
        -utilizationRate() uint32
        -memory() memoryInfo
        -temperature() float64
        -powerUsage() uint32
    }

    class cmd.memoryInfo {
        -used uint64
        -free uint64
        -total uint64
    }

    class cmd.nvidiaGPU {
        -index int
        -getDevice() (nvml.Device, error)
        -name() string
        -utilizationRate() uint32
        -memory() memoryInfo
        -temperature() float64
        -powerUsage() uint32
    }

' END DIAGRAM

' START SUBPACKAGES
' 'package cmd.backend {
    !include $rootUrl/backend/specs/class_diagram.puml
' }
' END SUBPACKAGES

' START IN-PACKAGE RELATIONS
    cmd.amdGPU <|.. cmd.GPU
    cmd.nvidiaGPU <|.. cmd.GPU
' END IN-PACKAGE RELATIONS