 ' START PREAMBLE

!$rootUrlLocal = ".."
!$rootUrlGitlab = "https://gitlab.com/nunet/device-management-service/-/raw/develop"

' package relative path: change this for each package
!$packageRelativePath = "/db"

!$packageUrlGitlab = $rootUrlGitlab + $packageRelativePath

' uncomment the following line to render all locally
' !$rootUrl = $rootUrlLocal
' uncomment the following line to render all from gitlab
!$rootUrl = $packageUrlGitlab

' END PREAMBLE

' START SUBPACKAGES
    !include $rootUrl/repositories/specs/class_diagram.puml
' END SUBPACKAGES