 ' START PREAMBLE

!$rootUrlLocal = ".."
!$rootUrlGitlab = "https://gitlab.com/nunet/device-management-service/-/raw/main"

' package relative path: change this for each package
!$packageRelativePath = "/network"

!$packageUrlGitlab = $rootUrlGitlab + $packageRelativePath

' uncomment the following line to render all locally
' !$rootUrl = $rootUrlLocal
' uncomment the following line to render all from gitlab
!$rootUrl = $packageUrlGitlab

' END PREAMBLE
 
 ' START DIAGRAM
    interface network.Network {
        +Init()
        +Start()
        +Stop()
        +Ping()
        +Advertise()
        +Unadvertise()
        +Publish()
        +Subscribe()
        +Stat()
    }

    class network.P2P {
        +Host host.Host
        +DHT *dht.IpfsDHT
        +PS peerstore.Peerstore
        -peers []peer.AddrInfo
        -config Libp2pConfig
        +Init()
        +Start()
        +Stop()
        +Ping()
        +Stat()
    }

    class network.DHT {
        +Advertise()
        +Unadvertise()
    }

    class network.Gossipsub {
        +Publish()
        +Subscribe()
    }

    interface network.Messaging {
        +New()
        +Send()
        +ReceiveHandler()
        +Close()
    }

' END DIAGRAM

' START SUBPACKAGES
'package network.libp2p {
    !include $rootUrl/libp2p/specs/class_diagram.puml
'}
' END SUBPACKAGES

' START IN-PACKAGE RELATIONS
network.P2P <|.. network.Network
network.DHT <|.. network.P2P
network.Gossipsub <|.. network.P2P
network.P2P <|.. network.Messaging
' END IN-PACKAGE RELATIONS
