package storage

import (
	"gitlab.com/nunet/device-management-service/models"
)

type IDType int
type VolumeSource string
type CreateVolOpt func(*models.StorageVolume)
type LockVolOpt func(*models.StorageVolume)

const (
	IDTypeUndefined IDType = iota
	IDTypePath
	IDTypeCID
)

const (
	VolumeSourceUndefined VolumeSource = "volume-source-undefined"
	VolumeSourceS3        VolumeSource = "s3"
	VolumeSourceIPFS      VolumeSource = "ipfs"
	VolumeSourceJob       VolumeSource = "job" // when data is generated by a job
)

// VolumeController is used to manage storage volumes.
//
// TODO-maybe: is the interface too big? We may have to split it?
type VolumeController interface {
	// CreateVolume creates a directory where data can be stored, and returns a StorageVolume
	// which contains the path to the directory.
	//
	// Be aware: CreateVolume does not insert any data within the directory. It's up to the caller
	// to do that.
	CreateVolume(volSource VolumeSource, opts ...CreateVolOpt) (models.StorageVolume, error)

	// LockVolume makes the volume read-only. It should be used after all necessary data has being written
	// to the volume. It makes clear if a volume will change state or not,that comes handy when we need
	// to retrieve volume's CID which is immutable given a certain data.
	//
	// One of the opts may be a CID. Or the implementation might handle the CID calculation
	//
	// TODO-maybe: after volume is locked, callers should not be able to write data to it.
	LockVolume(pathToVol string, opts ...LockVolOpt) error

	// DeleteVolume deletes everything within the volume's root directory.
	// Input can be either a path or a CID.
	DeleteVolume(identifier string, idType IDType) error

	// ListVolumes returns a list of all storage volumes managed by the VolumeController implementation
	ListVolumes() ([]models.StorageVolume, error)

	// GetSize returns the size of a volume
	// TODO-minor: identify which measurement type will be used
	GetSize(identifier string, idType IDType) (int64, error)

	// TODO-maybe: encrypt/decrypt method might move to an unique EncryptVolume/DecryptVolume interfaces
	// or something else.
	//  - Warning: if moved, EncryptionType field of StorageVolume must be updated somehow by the new interface
	EncryptVolume(path string, encryptor models.Encryptor, encryptionType models.EncryptionType) error
	DecryptVolume(path string, decryptor models.Decryptor, decryptionType models.EncryptionType) error
}
