package backend {
    interface cmd.backend.FileHandler {
        +Stat() os.FileInfo, error
        +WriteString(data string) int, error
    }

    interface cmd.backend.FileSystem {
        +Create(name string) (FileHandler, error)
        +MkdirAll(path string, perm os.FileMode) error
        +OpenFile(name string, flag int, perm os.FileMode) (FileHandler, error)
        +ReadFile(filename string) ([]byte, error)
        +RemoveAll(path string) error
        +Walk(root string, walkFn filepath.WalkFunc) error
    }

    class cmd.backend.OS {
        +Create(name string) (FileHandler, error)
        +FileInfoHeader(fi os.FileInfo, link string) (*tar.Header, error)
        +IsRegular(fi os.FileInfo) bool
        +MkdirAll(path string, perm os.FileMode) error
        +OpenFile(name string, flag int, perm os.FileMode) (FileHandler, error)
        +ReadFile(filename string) ([]byte, error)
        +RemoveAll(path string) error
        +Walk(root string, walkFn filepath.WalkFunc) error
    }

    interface cmd.backend.Logger {
        +AddMatch(match string) error
        +Close() error
        +GetEntry() (*sdjournal.JournalEntry, error)
        +Next() (uint64, error)
    }

    class cmd.backend.Journal {
        -journal *sdjournal.Journal
        +AddMatch(match string) error
        +Close() error
        +GetEntry() (*sdjournal.JournalEntry, error)
        +Next() (uint64, error)
    }

    interface cmd.backend.NetworkManager {
        +GetConnections(kind string) ([]net.ConnectionStat, error)
    }

    class cmd.backend.Network {
        +GetConnections(kind string) ([]net.ConnectionStat, error)
    }

    interface cmd.backend.PeerManager {
        +ClearIncomingChatRequests() error
        +Decode(s string) (peer.ID, error)
    }

    class cmd.backend.P2P {
        +ClearIncomingChatRequests() error
        +Decode(id string) (peer.ID, error)
    }

    interface cmd.backend.ResourceManager {
        +GetTotalProvisioned() *models.Provisioned
    }

    class cmd.backend.Resources {
        +GetTotalProvisioned() *models.Provisioned
    }

    interface cmd.backend.Utility {
        +IsOnboarded() (bool, error)
        +ReadMetadataFile() (*models.Metadata, error)
        +ResponseBody(c *gin.Context, method string, endpoint string, query string, body []byte) ([]byte, error)
    }

    class cmd.backend.Utils {
        +IsOnboarded() (bool, error)
        +ReadMetadataFile() (*models.Metadata, error)
        +ResponseBody(c *gin.Context, method string, endpoint string, query string, body []byte) ([]byte, error)
    }

    interface cmd.backend.WalletManager {
        +GetCardanoAddressAndMnemonic() (*models.BlockchainAddressPrivKey, error)
        +GetEthereumAddressAndPrivateKey() (*models.BlockchainAddressPrivKey, error)
    }

    class cmd.backend.Wallet {
        +GetCardanoAddressAndMnemonic() (*models.BlockchainAddressPrivKey, error)
        +GetEthereumAddressAndPrivateKey() (*models.BlockchainAddressPrivKey, error)
    }

    interface cmd.backend.WebSocketClient {
        +Initialize(url string) error
        +Close() error
        +ReadMessage(ctx context.Context, w io.Writer) error
        +WriteMessage(ctx context.Context, r io.Reader) error
        +Ping(ctx context.Context, w io.Writer) error
    }

    class cmd.backend.WebSocket {
        +Conn *websocket.Conn
        +Initialize(url string) error
        +Close() error
        +ReadMessage(ctx context.Context, w io.Writer) error
        +WriteMessage(ctx context.Context, r io.Reader) error
        +Ping(ctx context.Context, w io.Writer) error
    }
}
    cmd.backend.OS <|.. cmd.backend.FileSystem
    cmd.backend.Journal <|.. cmd.backend.Logger
    cmd.backend.Network <|.. cmd.backend.NetworkManager
    cmd.backend.P2P <|.. cmd.backend.PeerManager
    cmd.backend.Resources <|.. cmd.backend.ResourceManager
    cmd.backend.Utils <|.. cmd.backend.Utility
    cmd.backend.Wallet <|.. cmd.backend.WalletManager
    cmd.backend.WebSocket <|.. cmd.backend.WebSocketClient
