// Code generated by MockGen. DO NOT EDIT.
// Source: ../types/hardware.go
//
// Generated by this command:
//
//	mockgen -destination=mock_gpu_manager_test.go -source=../types/hardware.go -package=cmd -exclude_interfaces=HardwareManager,GPUConnector
//

// Package cmd is a generated GoMock package.
package cmd

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGPUManager is a mock of GPUManager interface.
type MockGPUManager struct {
	ctrl     *gomock.Controller
	recorder *MockGPUManagerMockRecorder
}

// MockGPUManagerMockRecorder is the mock recorder for MockGPUManager.
type MockGPUManagerMockRecorder struct {
	mock *MockGPUManager
}

// NewMockGPUManager creates a new mock instance.
func NewMockGPUManager(ctrl *gomock.Controller) *MockGPUManager {
	mock := &MockGPUManager{ctrl: ctrl}
	mock.recorder = &MockGPUManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUManager) EXPECT() *MockGPUManagerMockRecorder {
	return m.recorder
}

// GetGPUUsage mocks base method.
func (m *MockGPUManager) GetGPUUsage(uuid ...string) (types.GPUs, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range uuid {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGPUUsage", varargs...)
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUUsage indicates an expected call of GetGPUUsage.
func (mr *MockGPUManagerMockRecorder) GetGPUUsage(uuid ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUUsage", reflect.TypeOf((*MockGPUManager)(nil).GetGPUUsage), uuid...)
}

// GetGPUs mocks base method.
func (m *MockGPUManager) GetGPUs() (types.GPUs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUs")
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUs indicates an expected call of GetGPUs.
func (mr *MockGPUManagerMockRecorder) GetGPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUs", reflect.TypeOf((*MockGPUManager)(nil).GetGPUs))
}

// Shutdown mocks base method.
func (m *MockGPUManager) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGPUManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGPUManager)(nil).Shutdown))
}
