// Code generated by MockGen. DO NOT EDIT.
// Source: ../types/hardware.go
//
// Generated by this command:
//
//	mockgen -destination=mock_hardware_manager_test.go -source=../types/hardware.go -package=mocks
//

// Package mocks is a generated GoMock package.
package cmd

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockHardwareManager is a mock of HardwareManager interface.
type MockHardwareManager struct {
	ctrl     *gomock.Controller
	recorder *MockHardwareManagerMockRecorder
}

// MockHardwareManagerMockRecorder is the mock recorder for MockHardwareManager.
type MockHardwareManagerMockRecorder struct {
	mock *MockHardwareManager
}

// NewMockHardwareManager creates a new mock instance.
func NewMockHardwareManager(ctrl *gomock.Controller) *MockHardwareManager {
	mock := &MockHardwareManager{ctrl: ctrl}
	mock.recorder = &MockHardwareManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHardwareManager) EXPECT() *MockHardwareManagerMockRecorder {
	return m.recorder
}

// GetFreeResources mocks base method.
func (m *MockHardwareManager) GetFreeResources() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeResources")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeResources indicates an expected call of GetFreeResources.
func (mr *MockHardwareManagerMockRecorder) GetFreeResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeResources", reflect.TypeOf((*MockHardwareManager)(nil).GetFreeResources))
}

// GetMachineResources mocks base method.
func (m *MockHardwareManager) GetMachineResources() (types.MachineResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineResources")
	ret0, _ := ret[0].(types.MachineResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineResources indicates an expected call of GetMachineResources.
func (mr *MockHardwareManagerMockRecorder) GetMachineResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineResources", reflect.TypeOf((*MockHardwareManager)(nil).GetMachineResources))
}

// GetUsage mocks base method.
func (m *MockHardwareManager) GetUsage() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockHardwareManagerMockRecorder) GetUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockHardwareManager)(nil).GetUsage))
}
