// Code generated by MockGen. DO NOT EDIT.
// Source: ../executor/docker/client.go
//
// Generated by this command:
//
//	mockgen -destination=mock_docker_client_test.go -source=../executor/docker/client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package cmd

import (
	context "context"
	io "io"
	reflect "reflect"

	types "github.com/docker/docker/api/types"
	container "github.com/docker/docker/api/types/container"
	image "github.com/docker/docker/api/types/image"
	network "github.com/docker/docker/api/types/network"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// CreateContainer mocks base method.
func (m *MockClientInterface) CreateContainer(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, name string, pullImage bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, config, hostConfig, networkingConfig, platform, name, pullImage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockClientInterfaceMockRecorder) CreateContainer(ctx, config, hostConfig, networkingConfig, platform, name, pullImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockClientInterface)(nil).CreateContainer), ctx, config, hostConfig, networkingConfig, platform, name, pullImage)
}

// Exec mocks base method.
func (m *MockClientInterface) Exec(ctx context.Context, containerID string, cmd []string) (int, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, containerID, cmd)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Exec indicates an expected call of Exec.
func (mr *MockClientInterfaceMockRecorder) Exec(ctx, containerID, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockClientInterface)(nil).Exec), ctx, containerID, cmd)
}

// FindContainer mocks base method.
func (m *MockClientInterface) FindContainer(ctx context.Context, label, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContainer", ctx, label, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindContainer indicates an expected call of FindContainer.
func (mr *MockClientInterfaceMockRecorder) FindContainer(ctx, label, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContainer", reflect.TypeOf((*MockClientInterface)(nil).FindContainer), ctx, label, value)
}

// FollowLogs mocks base method.
func (m *MockClientInterface) FollowLogs(ctx context.Context, id string) (io.Reader, io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowLogs", ctx, id)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(io.Reader)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FollowLogs indicates an expected call of FollowLogs.
func (mr *MockClientInterfaceMockRecorder) FollowLogs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowLogs", reflect.TypeOf((*MockClientInterface)(nil).FollowLogs), ctx, id)
}

// GetImage mocks base method.
func (m *MockClientInterface) GetImage(ctx context.Context, imageName string) (image.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imageName)
	ret0, _ := ret[0].(image.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockClientInterfaceMockRecorder) GetImage(ctx, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockClientInterface)(nil).GetImage), ctx, imageName)
}

// GetOutputStream mocks base method.
func (m *MockClientInterface) GetOutputStream(ctx context.Context, containerID, since string, follow bool) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputStream", ctx, containerID, since, follow)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutputStream indicates an expected call of GetOutputStream.
func (mr *MockClientInterfaceMockRecorder) GetOutputStream(ctx, containerID, since, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputStream", reflect.TypeOf((*MockClientInterface)(nil).GetOutputStream), ctx, containerID, since, follow)
}

// InspectContainer mocks base method.
func (m *MockClientInterface) InspectContainer(ctx context.Context, id string) (types.ContainerJSON, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectContainer", ctx, id)
	ret0, _ := ret[0].(types.ContainerJSON)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectContainer indicates an expected call of InspectContainer.
func (mr *MockClientInterfaceMockRecorder) InspectContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectContainer", reflect.TypeOf((*MockClientInterface)(nil).InspectContainer), ctx, id)
}

// IsInstalled mocks base method.
func (m *MockClientInterface) IsInstalled(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInstalled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInstalled indicates an expected call of IsInstalled.
func (mr *MockClientInterfaceMockRecorder) IsInstalled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInstalled", reflect.TypeOf((*MockClientInterface)(nil).IsInstalled), ctx)
}

// PauseContainer mocks base method.
func (m *MockClientInterface) PauseContainer(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseContainer", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseContainer indicates an expected call of PauseContainer.
func (mr *MockClientInterfaceMockRecorder) PauseContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseContainer", reflect.TypeOf((*MockClientInterface)(nil).PauseContainer), ctx, containerID)
}

// PullImage mocks base method.
func (m *MockClientInterface) PullImage(ctx context.Context, imageName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, imageName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullImage indicates an expected call of PullImage.
func (mr *MockClientInterfaceMockRecorder) PullImage(ctx, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockClientInterface)(nil).PullImage), ctx, imageName)
}

// RemoveContainer mocks base method.
func (m *MockClientInterface) RemoveContainer(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockClientInterfaceMockRecorder) RemoveContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockClientInterface)(nil).RemoveContainer), ctx, containerID)
}

// RemoveObjectsWithLabel mocks base method.
func (m *MockClientInterface) RemoveObjectsWithLabel(ctx context.Context, label, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObjectsWithLabel", ctx, label, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObjectsWithLabel indicates an expected call of RemoveObjectsWithLabel.
func (mr *MockClientInterfaceMockRecorder) RemoveObjectsWithLabel(ctx, label, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObjectsWithLabel", reflect.TypeOf((*MockClientInterface)(nil).RemoveObjectsWithLabel), ctx, label, value)
}

// ResumeContainer mocks base method.
func (m *MockClientInterface) ResumeContainer(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeContainer", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeContainer indicates an expected call of ResumeContainer.
func (mr *MockClientInterfaceMockRecorder) ResumeContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeContainer", reflect.TypeOf((*MockClientInterface)(nil).ResumeContainer), ctx, containerID)
}

// StartContainer mocks base method.
func (m *MockClientInterface) StartContainer(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContainer", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContainer indicates an expected call of StartContainer.
func (mr *MockClientInterfaceMockRecorder) StartContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContainer", reflect.TypeOf((*MockClientInterface)(nil).StartContainer), ctx, containerID)
}

// StopContainer mocks base method.
func (m *MockClientInterface) StopContainer(ctx context.Context, containerID string, options container.StopOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", ctx, containerID, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockClientInterfaceMockRecorder) StopContainer(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockClientInterface)(nil).StopContainer), ctx, containerID, options)
}

// WaitContainer mocks base method.
func (m *MockClientInterface) WaitContainer(ctx context.Context, containerID string) (<-chan container.WaitResponse, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitContainer", ctx, containerID)
	ret0, _ := ret[0].(<-chan container.WaitResponse)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// WaitContainer indicates an expected call of WaitContainer.
func (mr *MockClientInterfaceMockRecorder) WaitContainer(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitContainer", reflect.TypeOf((*MockClientInterface)(nil).WaitContainer), ctx, containerID)
}
