.TH NUNET 1 "September 2024" "NuNet CLI" "User Commands"

.SH NAME
nunet \- command-line interface for the device management service (DMS)

.SH SYNOPSIS
.B nunet
[\fIOPTIONS\fR] \fICOMMAND\fR

.SH DESCRIPTION
The NuNet Command-Line Interface (CLI) is a powerful tool for interacting with the NuNet Device Management Service (DMS). It enables users to manage network configurations, control capabilities, handle cryptographic keys and interact with actors.

.SH COMMANDS
.TP
.B nunet actor
Interact with the NuActor System.
.TP
.B nunet cap
Manage capabilities.
.TP
.B nunet config
Manage the configuration file.
.TP
.B nunet gpu
List or test available GPUs.
.TP
.B nunet key
Manage keys/identities.
.TP
.B nunet network
Utility tool for managing deployment networks.
.TP
.B nunet run
Start the NuNet Device Management Service (DMS) process. It initializes and connects a node to the network.
.TP
.B nunet version
Display version and additional information for the current build.

.SH OPTIONS
Options vary depending on the command. Use \fBnunet [COMMAND] --help\fR for command-specific options.

.SH CONFIGURATION MANAGEMENT
NuNet DMS uses a configuration file to manage some settings. DMS looks for a \fIdms_config.json\fR file in one of the following paths, listed in order of priority:
.RS
.IP 1.
Current directory (\fI.\fR)
.IP 2.
User-level (\fI$HOME/.nunet\fR)
.IP 3.
System-wide directory (\fI/etc/nunet\fR)
.RE
The configuration file must be in JSON format and allows you to configure several parameters. For a full list of configurable parameters, run \fBnunet config edit\fR after setting the \fIEDITOR\fR environment variable to your preferred editor; this will open the default configuration in that editor.

.TP
.B nunet config edit
Open the configuration file with the default text editor.
.TP
.B nunet config get \fIKEY\fR
Retrieve the current value of a specific configuration key. If no key is provided, displays the entire configuration as JSON.
.TP
.B nunet config set \fIKEY\fR \fIVALUE\fR
Set a new value for a specific configuration key. Creates the configuration file if it does not exist.

.SH KEY MANAGEMENT
Cryptographic keys are necessary for authorization and authentication in NuNet. All keys are associated with a Decentralized Identifier (DID) and stored under user configuration directory. Additionally, NuNet supports the use of hardware wallets, specifically Ledger devices, for enhanced security.

.TP
.B nunet key new \fI<CONTEXT_NAME>\fR
Generate a new keypair and store it securely. By default, keys are generated using Ed25519 scheme. If a key with the specified name already exists, the user will be prompted to confirm before overwriting it.
.TP
.B nunet key did \fI<CONTEXT_NAME>\fR | \fIledger\fR | \fIledger:<INDEX>\fR | \fIledger:<ALIAS>\fR
Retrieve the DID associated with a specified context. Supports ledger accounts (by index or alias) in addition to retrieving from local keystore.
.TP
.B nunet key ledger-alias set \fI<ALIAS>\fR \fI<INDEX>\fR
Create or update a Ledger account aliases.

.SH CAPABILITY MANAGEMENT
Capabilities are a key concept in NuNet's security model. A capability is a communicable and unforgeable token of authority. To perform any operation on NuNet, you must have the necessary capabilities. The NuNet CLI provides commands to create, modify, delegate, and list capabilities.

.TP
.B nunet cap new \fI<CONTEXT_NAME>\fR
Create a new persistent capability context for DMS or for user. If a key doesn't exist for the specified context, a new one will be created. Supports ledger accounts (by index or alias) in addition to retrieving from local keystore.

\fBIMPORTANT\fR: Generally, for each key created with \fBnunet key new\fR, you must create a capability with the same name.

.TP
.B nunet cap anchor [\fIOPTIONS\fR]
Add or modify capability anchors in a capability context. Anchors serve as the foundation for defining capabilities, establishing core permissions and restrictions.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the operation context (default: "user").
.TP
\fB--provide\fR \fISTRING\fR
Add tokens as a "provide" anchor in JSON format.
.TP
\fB--require\fR \fISTRING\fR
Add tokens as a "require" anchor in JSON format.
.TP
\fB--root\fR \fISTRING\fR
Add a DID as a "root" anchor.
.RE

.TP
.B nunet cap delegate \fI<subjectDID>\fR [\fIOPTIONS\fR]
Delegate specific capabilities to a subject, granting them permissions within the system. Capabilities are delegated based on set \fBprovide\fR anchors.
.RS
.TP
\fB-a, --audience\fR \fISTRING\fR
Specify the audience DID (optional).
.TP
\fB--cap\fR \fISTRINGS\fR
Define the capabilities to be granted or delegated (can be specified multiple times).
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the operation context (default: "user").
.TP
\fB-d, --depth\fR \fIUINT\fR
Set the delegation depth (default: 0).
.TP
\fB--duration\fR \fIDURATION\fR
Set the duration for which the delegation is valid.
.TP
\fB-e, --expiry\fR \fITIME\fR
Set an expiration time for the delegation.
.TP
\fB--auto-expire\fR
Automatically set the expiration time of the token right above on the delegation chain.
.TP
\fB--self-sign\fR \fISTRING\fR
Specify self-signing options: 'no' (default), 'also', or 'only'.
.TP
\fB-t, --topic\fR \fISTRINGS\fR
Define the topics for which capabilities are granted or delegated (can be specified multiple times).
.RE

.TP
.B nunet cap grant \fI<subjectDID>\fR [\fIOPTIONS\fR]
Grant (delegate) capabilities having the granter as root issuer. Granting is a self-signed operation by default.
.RS
.TP
\fB-a, --audience\fR \fISTRING\fR
Specify the audience DID (optional).
.TP
\fB--cap\fR \fISTRINGS\fR
Define the capabilities to be granted or delegated.
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the operation context (default: "user").
.TP
\fB-d, --depth\fR \fIUINT\fR
Set the delegation depth.
.TP
\fB--duration\fR \fIDURATION\fR
Set the duration for which the grant is valid.
.TP
\fB-e, --expiry\fR \fITIME\fR
Set an expiration time for the grant.
.TP
\fB-t, --topic\fR \fISTRINGS\fR
Define the topics for which capabilities are granted.
.RE

.TP
.B nunet cap list [\fIOPTIONS\fR]
List all capability anchors in a capability context. Outputs DIDs for root and capability tokens set on provide, require and revoke anchors.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the operation context (default: "user").
.RE

.TP
.B nunet cap remove [\fIOPTIONS\fR]
Remove capability anchors from a capability context. One capability token at a time.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the operation context (default: "user").
.TP
\fB--provide\fR \fISTRING\fR
Remove tokens from the "provide" anchor in JSON format.
.TP
\fB--require\fR \fISTRING\fR
Remove tokens from the "require" anchor in JSON format.
.TP
\fB--root\fR \fISTRING\fR
Remove a DID from the "root" anchor.
.RE

.TP
.B nunet cap revoke \fI<TOKEN>\fR [\fIOPTIONS\fR]
Revoke a granted or delegated token.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the context to use for the operation (required).
.RE

.SH ACTOR SYSTEM
The NuActor System is an implementation of the Actor Model. Actors are entities that communicate via immutable messages. The \fBnunet actor\fR command has the following subcommands for interacting with the actor system.

.TP
.B nunet actor msg \fI<behavior>\fR \fI<payload>\fR [\fIOPTIONS\fR]
Construct and sign a message that can be communicated to an actor. The constructed message is returned as a JSON object that can be stored or piped into another command.
.RS
.TP
\fB-b, --broadcast\fR \fISTRING\fR
Designate the topic for broadcasting the message.
.TP
\fB-c, --context\fR \fISTRING\fR
Specify the capability context name.
.TP
\fB-d, --dest\fR \fISTRING\fR
Identify the destination handle for the message.
.TP
\fB-e, --expiry\fR \fITIME\fR
Set an expiration time for the message.
.TP
\fB-i, --invoke\fR
Mark the message as an invocation, requesting a response from the actor.
.TP
\fB-t, --timeout\fR \fIDURATION\fR
Set a timeout for awaiting a response after invoking a behavior.
.RE

.TP
.B nunet actor send \fI<msg>\fR
Send a previously constructed message to an actor. Actors only communicate via messages.

.TP
.B nunet actor invoke \fI<msg>\fR
Directly invoke a specific behavior on an actor and expect a response.

.TP
.B nunet actor broadcast \fI<msg>\fR
Disseminate a message to a designated topic, potentially reaching multiple actors.

.TP
.B nunet actor cmd [\fICOMMAND\fR] [\fIOPTIONS\fR]
Invoke a predefined public behavior on an actor. To list all available subcommands, use the \fB--help\fR option.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Capability context name.
.TP
\fB-d, --dest\fR \fISTRING\fR
Destination DMS DID, peer ID or handle.
.TP
\fB-e, --expiry\fR \fITIME\fR
Expiration time.
.TP
\fB-t, --timeout\fR \fIDURATION\fR
Timeout duration.
.RE

The \fBactor cmd\fR command is used to send messages to an actor through the command line. There are behaviors specifically designated for use with the command line.
The following are the implemented behaviors and their associated capabilities:
.TP
.B /public/hello
Invoke a "hello" message for a polite introduction.
.RS
Examples:
.B nunet actor cmd --context user /public/hello
.B nunet actor cmd --context user /public/hello --dest <did/peer_id/actor_handle>
.RE

.TP
.B /broadcast/hello
Broadcast a "hello" message to a topic for polite introduction.
.RS
Examples:
.B nunet actor cmd --context user /broadcast/hello
.RE

.TP
.B /public/status
Retrieve actor status and resources information.
.RS
Examples:
.B nunet actor cmd --context user /public/status
.B nunet actor cmd --context user /public/status --dest <did/peer_id/actor_handle>
.RE

.TP
.B /dms/node/status
Invoke a "status discovery" message for fleet discovery.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/status
.B nunet actor cmd --context user /dms/node/status --dest <did/peer_id/actor_handle>
.RE

.TP
.B /broadcast/dms/status
Broadcast a "status discovery" message to topic /nunet/status for fleet discovery.
.RS
Examples:
.B nunet actor cmd --context user /broadcast/dms/status
.RE

.TP
.B /dms/node/peers/list
List connected peers.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/peers/list
.B nunet actor cmd --context user /dms/node/peers/list [--dest <did/peer_id/actor_handle>]
.RE

.TP
.B /dms/node/peers/self
Get peer's ID and addresses.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/peers/self
.B nunet actor cmd --context user /dms/node/peers/self [--dest <did/peer_id/actor_handle>]
.RE

.TP
.B /dms/node/peers/ping
Ping a peer.
.RS
\fB--host\fR \fISTRING\fR (required): host address to ping
Examples:
.B nunet actor cmd --context user /dms/node/peers/ping --host <peer_id>
.RE

.TP
.B /dms/node/peers/dht
List peers connected to DHT.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/peers/dht
.RE

.TP
.B /dms/node/peers/connect
Connect to a peer.
.RS
\fB--address\fR \fISTRING\fR (required): peer address to connect to
Examples:
.B nunet actor cmd --context user /dms/node/peers/connect --address /p2p/<peer_id>
.RE

.TP
.B /dms/node/peers/score
Retrieve gossipsub broadcast score.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/peers/score
.RE

.TP
.B /dms/node/onboarding/onboard
Onboard a node to the network.
.RS
\fB--ram\fR, \fB--cpu\fR, \fB--disk\fR (required): set resources to reserve
Examples:
.B nunet actor cmd --context user /dms/node/onboarding/onboard --disk 1 --ram 1 --cpu 2
.RE

.TP
.B /dms/node/onboarding/offboard
Offboard a node from the network.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/onboarding/offboard
.RE

.TP
.B /dms/node/onboarding/status
Retrieve onboarding status of a node.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/onboarding/status
.RE

.TP
.B /dms/node/deployment/list
List deployments.
.RS
\fB--filter\fR: metadata filter (optional)
Examples:
.B nunet actor cmd --context user /dms/node/deployment/list --filter "<metadata_key>=<metadata_value>"
.RE

.TP
.B /dms/node/deployment/prune
Prune old deployments.
.RS
\fB--before\fR: remove deployments created before this time
\fB--all\fR: remove all deployments whose status is greater than Running
Examples:
.B nunet actor cmd --context user /dms/node/deployment/prune --before 2025-01-01T00:00:00Z
.B nunet actor cmd --context user /dms/node/deployment/prune --all
.RE

.TP
.B /dms/node/deployment/status
Get deployment status.
.RS
\fB--id\fR \fISTRING\fR (required): deployment ID
Examples:
.B nunet actor cmd --context user /dms/node/deployment/status --id <deployment_id>
.RE

.TP
.B /dms/node/deployment/logs
Get deployment logs.
.RS
\fB--id\fR \fISTRING\fR (required): ensemble ID
\fB--allocation\fR \fISTRING\fR (required): allocation name
Examples:
.B nunet actor cmd --context user /dms/node/deployment/logs --id <deployment_id> --allocation <allocation_name>
.RE

.TP
.B /dms/node/deployment/manifest
Get deployment manifest.
.RS
\fB--id\fR \fISTRING\fR (required): deployment ID
Examples:
.B nunet actor cmd --context user /dms/node/deployment/manifest --id <deployment_id>
.RE

.TP
.B /dms/node/deployment/shutdown
Shutdown a deployment.
.RS
\fB--id\fR \fISTRING\fR (required): deployment ID
Examples:
.B nunet actor cmd --context user /dms/node/deployment/shutdown --id <deployment_id>
.RE

.TP
.B /dms/node/deployment/new
Create a new deployment.
.RS
\fB--spec-file\fR: path to ensemble specification file
Examples:
.B nunet actor cmd --context user /dms/node/deployment/new --spec-file <ensemble.yaml>
.RE

.TP
.B /dms/node/deployment/update
Update an existing deployment.
.RS
\fB--spec-file\fR: path to ensemble specification file
\fB--id\fR \fISTRING\fR (required): ensemble ID
Examples:
.B nunet actor cmd --context user /dms/node/deployment/update --spec-file <ensemble.yaml> --id <ensemble_id>
.RE

.TP
.B /dms/node/resources/allocated
Get allocated resources.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/resources/allocated
.RE

.TP
.B /dms/node/resources/free
Get free resources.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/resources/free
.RE

.TP
.B /dms/node/resources/onboarded
Get onboarded resources.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/resources/onboarded
.RE

.TP
.B /dms/node/allocations/list
List allocations.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/allocations/list
.RE

.TP
.B /dms/node/logger/config
Adjust logger settings.
.RS
\fB--level\fR, \fB--url\fR, \fB--interval\fR, \fB--api-key\fR, \fB--apm-url\fR, \fB--enable-elastic\fR
Examples:
.TP
.B nunet actor cmd --context user /dms/node/logger/config --level debug
.TP
.B nunet actor cmd --context user /dms/node/logger/config --url <elasticsearch-url>
.TP
.B nunet actor cmd --context user /dms/node/logger/config --interval 10
.TP
.B nunet actor cmd --context user /dms/node/logger/config --api-key <api-key>
.TP
.B nunet actor cmd --context user /dms/node/logger/config --apm-url <apm-url>
.TP
.B nunet actor cmd --context user /dms/node/logger/config --enable-elastic
.TP
.RE

.TP
.B /dms/node/hardware/spec
Get hardware specifications.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/hardware/spec
.RE

.TP
.B /dms/node/hardware/usage
Get hardware usage.
.RS
Examples:
.B nunet actor cmd --context user /dms/node/hardware/usage
.RE

.TP
.B /dms/cap/list
List capabilities.
.RS
\fB--context\fR: context name
Examples:
.B nunet actor cmd --context user /dms/cap/list
.RE

.TP
.B /dms/cap/anchor
Add capability anchors.
.RS
\fB--root\fR, \fB--require\fR, \fB--provide\fR, \fB--revoke\fR (one required)
Examples:
.B nunet actor cmd --context user /dms/cap/anchor --root did
.B nunet actor cmd --context user /dms/cap/anchor --require token
.B nunet actor cmd --context user /dms/cap/anchor --provide token
.B nunet actor cmd --context user /dms/cap/anchor --revoke token
.RE

.TP
.B /dms/node/deployment/delete
Delete a specific deployment.
.RS
\fB--id\fR \fISTRING\fR (required): deployment ID
Examples:
.B nunet actor cmd --context user /dms/node/deployment/delete --id <deployment-id>
.RE

.TP
.B /dms/volume/create
Create a new volume.
.RS
\fB--name\fR, \fB--client-pem-file\fR, \fB--ca-output-dir\fR (all required)
Examples:
.B nunet actor cmd --context user /dms/volume/create --name <volname> --client-pem-file <filename>
.RE

.TP
.B /dms/volume/delete
Delete a volume.
.RS
\fB--name\fR \fISTRING\fR (required): volume name
Examples:
.B nunet actor cmd --context user /dms/volume/delete --name <volname>
.RE

.TP
.B /dms/volume/start
Start a volume.
.RS
\fB--name\fR \fISTRING\fR (required): volume name
Examples:
.B nunet actor cmd --context user /dms/volume/start --name <volname>
.RE

.TP
.B /dms/tokenomics/contract/create
Create a new contract.
.RS
\fB--contract-file\fR \fISTRING\fR (required): contract file path
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/create --contract-file <file> --dest <did_of_solution_enabler>
.RE

.TP
.B /dms/tokenomics/contract/aprove_local
Send a contract approval request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/aprove_local --contract-did <did>
.RE

.TP
.B /dms/tokenomics/contract/list_incoming
List incoming contracts.
.RS
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/list_incoming
.RE

.TP
.B /dms/tokenomics/contract/transactions/list
List contract transactions.
.RS
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/transactions/list
.RE

.TP
.B /dms/tokenomics/contract/transactions/confirm
Confirm a contract transaction.
.RS
\fB--unique-id\fR \fISTRING\fR (required)
\fB--tx-hash\fR \fISTRING\fR (required)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/transactions/confirm --unique-id <uniqueid> --tx-hash <txhash>
.RE

.TP
.B /dms/tokenomics/contract/usages/calculate
Send a usage calculation request.
.RS
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/usages/calculate
.RE

.TP
.B /dms/tokenomics/contract/payment/status
Send a payment status request.
.RS
\fB--unique-id\fR \fISTRING\fR (required)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/payment/status --unique-id <uniqueid>
.RE

.TP
.B /dms/tokenomics/contract/state
Send a contract state request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
\fB--contract-host-did\fR \fISTRING\fR (optional)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/state --contract-did <did> --contract-host-did <hostdid>
.RE

.TP
.B /dms/tokenomics/contract/validate
Send a contract validate request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
\fB--contract-host-did\fR \fISTRING\fR (optional)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/validate --contract-did <did> --contract-host-did <hostdid>
.RE

.TP
.B /dms/tokenomics/contract/complete
Send a contract complete request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
\fB--contract-host-did\fR \fISTRING\fR (optional)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/complete --contract-did <did> --contract-host-did <hostdid>
.RE

.TP
.B /dms/tokenomics/contract/terminate
Send a contract termination request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
\fB--contract-host-did\fR \fISTRING\fR (optional)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/terminate --contract-did <did> --contract-host-did <hostdid>
.RE

.TP
.B /dms/tokenomics/contract/settle
Send a contract settle request.
.RS
\fB--contract-did\fR \fISTRING\fR (required)
\fB--contract-host-did\fR \fISTRING\fR (optional)
Examples:
.B nunet actor cmd --context user /dms/tokenomics/contract/settle --contract-did <did> --contract-host-did <hostdid>
.RE



.SH GPU MANAGEMENT
Manage GPU resources.

.TP
.B nunet gpu list
List all available GPUs with detailed information including model, VRAM, vendor, PCI address, UUID, and index.

.TP
.B nunet gpu test
Test GPU by running a Docker container with GPU resources. Automatically selects the GPU with maximum free VRAM.

.SH NETWORK UTILITY
Network utility tool for managing deployment networks.

.TP
.B nunet network ls [\fIOPTIONS\fR]
List all deployment networks the DMS is part of.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Specify a capability context (required).
.TP
\fB-v, --verbose\fR
Enable verbose output showing allocation and network details.
.RE

.TP
.B nunet network show [\fIOPTIONS\fR]
Show details of a specific network.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Capability context (required).
.TP
\fB-i, --id\fR \fISTRING\fR
Deployment/Ensemble ID (required).
.RE

.TP
.B nunet network attach [\fIOPTIONS\fR]
Attach to a deployment network. Currently only ssh supported.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Capability context (required).
.TP
\fB-i, --id\fR \fISTRING\fR
Deployment ID (required).
.TP
\fB-a, --alloc\fR \fISTRING\fR
Allocation ID (required).
.TP
\fB--shell\fR
Open an SSH shell to the allocation.
.TP
\fB--forward\fR
Set up port forwarding. (Not Implemented)
.TP
\fB--username\fR \fISTRING\fR
SSH username.
.TP
\fB--identity\fR \fISTRING\fR
SSH private key file path.
.TP
\fB--port\fR \fISTRING\fR
Port to attach to. SSH listening port in case of --shell
.TP
\fB--port-map\fR \fISTRING\fR
Port mapping configuration. (Not Implemented)
.RE

.SH RUN THE DEVICE MANAGEMENT SERVICE

.TP
.B nunet run [\fIOPTIONS\fR]
Start the Device Management Service (DMS). The DMS is a system application for running a node in the NuNet decentralized network of compute providers. By default, DMS listens on port 9999.
.RS
.TP
\fB-c, --context\fR \fISTRING\fR
Capability context name (default: "dms").
.RE

.SH EXAMPLES
.TP
Generate a new keypair:
.B nunet key new mykey
.TP
Retrieve the DID associated with a key:
.B nunet key did mykey
.TP
Create a Ledger alias:
.B nunet key ledger-alias set business 3
.TP
Start the DMS:
.B nunet run
.TP
List available GPUs:
.B nunet gpu list
.TP
Test GPU deployment:
.B nunet gpu test
.TP
Create a new capability context:
.B nunet cap new mycapability
.TP
Add a "provide" anchor to a capability context:
.B nunet cap anchor --context mycapability --provide '{"action": "read"}'
.TP
Delegate a capability to another DID:
.B nunet cap delegate did:example:123 --cap /public --topic /nunet/public
.TP
Revoke a capability token:
.B nunet cap revoke --context user '{"some": "json", "token": "here"}'
.TP
Remove a capability anchor:
.B nunet cap remove --context user --root did:key:abcd1234
.TP
List networks:
.B nunet network ls --context dms
.TP
Show network details:
.B nunet network show --context dms --id deployment123
.TP
Attach to network allocation:
.B nunet network attach --shell --context dms --id deployment123 --alloc alloc1
.TP
Construct and send a message to an actor:
.B nunet actor msg /public/hello 'Hello, World!' --dest did:example:456 | nunet actor send
.TP
Invoke a predefined command on an actor:
.B nunet actor cmd --context dms /dms/node/peers/list

.SH NOTES
.IP \[bu] 2
Some commands may require root privileges.
.IP \[bu]
Be cautious when configuring network settings to avoid disrupting network connectivity.
.IP \[bu]
Keep private keys secure, as they provide access to your identity and associated capabilities within the NuNet DMS.

.SH SEE ALSO
For more detailed information on specific commands, use the \fB--help\fR option with any command.

.SH AUTHOR
Written and maintained by Gustavo Silva <gustavo.silva@nunet.io>.

.SH ENVIRONMENT
.TP
.B DMS_PASSPHRASE
If set, this environment variable shares the passphrase across all cryptographic keys stored, avoiding interactive prompts. Use with caution to prevent exposing the passphrase.

.SH REPORTING BUGS
Report bugs to the NuNet issue tracker at <https://gitlab.com/nunet/device-management-service/-/issues>
