
'package dms.jobs {
    !include ../jobs/specs/class_diagram.puml
'}

'package dms.node {
    !include ../node/specs/class_diagram.puml
'}

'package dms.onboarding {
    !include ../onboarding/specs/class_diagram.puml
'}

'package dms.orchestrator {
    !include ../orchestrator/specs/class_diagram.puml
'}

'package dms.resources {
    !include ../resources/specs/class_diagram.puml
'}

dms.node.Actor ..|> dms.node.Node
dms.node.Actor ..|> dms.jobs.Allocation
dms.orchestrator.Orchestrator ..|> dms.node.Node
dms.orchestrator.graph.Vertex ..|> dms.node.Node

