#!/bin/bash

echo Running postinst script.

USER=nunet

# if there is no such user, create it
adduser --system --no-create-home --quiet $USER
addgroup --system $USER
adduser $USER $USER
adduser $USER docker

# Give above user access to write to /etc/nunet
chown -R $USER:$USER /var/nunet

# Start the services.
systemctl daemon-reload

if command -v mandb > /dev/null; then
    echo Adding man page.
    mandb -q
fi

# Generate and install bash completion script
if [ -d /etc/bash_completion.d ]; then
    /usr/bin/nunet completion bash > /etc/bash_completion.d/nunet.sh
    echo "Bash completion installed. Restart your shell or source /etc/bash_completion.d/nunet.sh"
fi

# Generate and install zsh completion script
if [ -d /usr/share/zsh/vendor-completions ]; then
    /usr/bin/nunet completion zsh > /usr/share/zsh/vendor-completions/_nunet
    echo "Zsh completion installed. Restart your shell or re-init completion with 'compinit'"
fi

# Set necessary capabilities for network administration
if [ -x "$(command -v setcap)" ]; then
    setcap cap_net_admin+ep /usr/bin/nunet
    echo "Network capabilities set for nunet binary"
else
    echo "Warning: setcap command not found. Unable to set network capabilities for nunet binary."
    echo "You may need to run nunet with elevated privileges or manually set the network capabilities."
    echo "For manual setting, install `libcap2-bin` for Debian/Ubuntu or `libcap` for CentOS/RHEL/Arch"
    echo "After installing, run `sudo setcap cap_net_admin+ep /usr/bin/nunet`"
fi
