#!/bin/bash

systemctl daemon-reload

# don't need to remove the group because the group is deleted along with the user
# given that group only has that particular user
if [ -x "$(command -v deluser)" ]; then
     deluser --quiet --system nunet > /dev/null || true
  else
     echo >&2 "not removing nunet system account because deluser command was not found"
fi

if [ $1 = "purge" ]; then
    rm -rf /var/nunet
    rm -rf /usr/share/man/man1/nunet.1.gz
    if command -v mandb > /dev/null; then
        mandb -q
    fi
fi
