#!/bin/bash

echo "Running pre installation script ..."

# Pre-install script for nunet-dms. 

# Part 1: Remove old version of nunet-dms if it exists.
# 0. Stop running service. Remove the service unit files.
# 1. Remove binary file.
# 2. Remove config files at /etc/nunet

echo "Stopping service and removing service unit files ..."

systemctl daemon-reload

if [ -f "/etc/systemd/system/nunet.service" ];then
    systemctl stop nunet.service
    rm /etc/systemd/system/nunet.service
fi

echo "Looking for old versions of nunet-dms ..."

if [ -f "/usr/bin/nunet" ];then
    rm -f /usr/bin/nunet
    echo "Removed old nunet binary from /usr/bin ..."
fi
