// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../types/hardware.go
//
// Generated by this command:
//
//	mockgen -destination=mock_gpu_connector_test.go -source=../../../types/hardware.go -package=gpu -exclude_interfaces=HardwareManager,GPUManager
//

// Package gpu is a generated GoMock package.
package gpu

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGPUConnector is a mock of GPUConnector interface.
type MockGPUConnector struct {
	ctrl     *gomock.Controller
	recorder *MockGPUConnectorMockRecorder
}

// MockGPUConnectorMockRecorder is the mock recorder for MockGPUConnector.
type MockGPUConnectorMockRecorder struct {
	mock *MockGPUConnector
}

// NewMockGPUConnector creates a new mock instance.
func NewMockGPUConnector(ctrl *gomock.Controller) *MockGPUConnector {
	mock := &MockGPUConnector{ctrl: ctrl}
	mock.recorder = &MockGPUConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUConnector) EXPECT() *MockGPUConnectorMockRecorder {
	return m.recorder
}

// GetGPUUsage mocks base method.
func (m *MockGPUConnector) GetGPUUsage(uuid string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUUsage", uuid)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUUsage indicates an expected call of GetGPUUsage.
func (mr *MockGPUConnectorMockRecorder) GetGPUUsage(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUUsage", reflect.TypeOf((*MockGPUConnector)(nil).GetGPUUsage), uuid)
}

// GetGPUs mocks base method.
func (m *MockGPUConnector) GetGPUs() (types.GPUs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUs")
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUs indicates an expected call of GetGPUs.
func (mr *MockGPUConnectorMockRecorder) GetGPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUs", reflect.TypeOf((*MockGPUConnector)(nil).GetGPUs))
}

// Shutdown mocks base method.
func (m *MockGPUConnector) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGPUConnectorMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGPUConnector)(nil).Shutdown))
}
