 ' START PREAMBLE

!$rootUrlLocal = ".."
!$rootUrlGitlab = "https://gitlab.com/nunet/device-management-service/-/raw/develop"

' package relative path: change this for each package
!$packageRelativePath = ""

!$packageUrlGitlab = $rootUrlGitlab + $packageRelativePath

' uncomment the following line to render all locally
' !$rootUrl = $rootUrlLocal
' uncomment the following line to render all from gitlab
!$rootUrl = $packageUrlGitlab

' END PREAMBLE

left to right direction
'top to bottom direction

' comment to show all classes that are not yet described in the diagram
hide <<hide>>


' START DIAGRAM
' END DIAGRAM

' START SUBPACKAGES

' package api {
 !include $rootUrl/api/specs/class_diagram.puml
' }

'package cmd {
    !include $rootUrl/cmd/specs/class_diagram.puml
'}

'package db {
    !include $rootUrl/db/specs/class_diagram.puml
'}

'package dms {
    !include $rootUrl/dms/specs/class_diagram.puml
'}

'package executor {
    !include $rootUrl/executor/specs/class_diagram.puml
'}

'package internal {
    !include $rootUrl/internal/specs/class_diagram.puml
'}

'package models {
    !include $rootUrl/models/specs/class_diagram.puml
'}

'package network {
    !include $rootUrl/network/specs/class_diagram.puml
'}

'package plugins {
    !include $rootUrl/plugins/specs/class_diagram.puml
'}

'package storage {
    !include $rootUrl/storage/specs/class_diagram.puml
'}

'package telemetry {
    !include $rootUrl/telemetry/specs/class_diagram.puml
'}

'package tokenomics {
    !include $rootUrl/tokenomics/specs/class_diagram.puml
'}

'package utils {
    !include $rootUrl/utils/specs/class_diagram.puml
'}

' START INTER-PACKAGE RELATIONS
models.ID ..|> dms.jobs.AllocationID

dms.orchestrator.matching.ComparatorMap::ExecutorsComparator <|-- models.Executors 
dms.orchestrator.matching.ComparatorMap::ExecutorTypeComparator <|-- models.ExecutorType
dms.orchestrator.matching.ComparatorMap::GPUsComparator <|-- models.GPUs
dms.orchestrator.matching.ComparatorMap::GPUVendorComparator <|-- models.GPUVendor
dms.orchestrator.matching.ComparatorMap::GPUComparator <|-- models.GPU
dms.orchestrator.matching.ComparatorMap::JobTypesComparator <|-- models.JobTypes
dms.orchestrator.matching.ComparatorMap::LibraryComparator <|-- models.Library
dms.orchestrator.matching.ComparatorMap::LocalityComparator <|-- models.Locality


dms.orchestrator.matching.Comparator::Compare <|-- models.Comparison 

models.ID ..|> dms.node.NodeID

db.repositories.GenericRepository <|.. telemetry.DatabaseCollector

dms.node.Actor -- network.libp2p.P2P

' END INTER-PACKAGE RELATIONS