  ' START DIAGRAM
    class db.repositories.repositories_gorm.GenericEntityRepositoryGorm {
        -db *gorm.DB
        +GetQuery() repositories.Query
        +Save(data T) T, error
        +Get() T, error
        +Clear() error
        +History(query repositories.Query) []T, error
    }

    class db.repositories.repositories_gorm.GenericRepositoryGorm {
        -db *gorm.DB
        +GetQuery() repositories.Query
        +Create(data T) T, error
        +Get(id interface) T, error
        +Update(id interface, data T) T, error
        +Delete(id interface) error
        +Find(query repositories.Query) T, error
        +FindAll(query repositories.Query) []T, error
    }
' END DIAGRAM