// Code generated by MockGen. DO NOT EDIT.
// Source: ../../types/resource.go
//
// Generated by this command:
//
//	mockgen -destination=mock_system_specs_test.go -source=../../types/resource.go -package=resources -exclude_interfaces=UsageMonitor,ResourceManager,ResourceOps
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemSpecs is a mock of SystemSpecs interface.
type MockSystemSpecs struct {
	ctrl     *gomock.Controller
	recorder *MockSystemSpecsMockRecorder
}

// MockSystemSpecsMockRecorder is the mock recorder for MockSystemSpecs.
type MockSystemSpecsMockRecorder struct {
	mock *MockSystemSpecs
}

// NewMockSystemSpecs creates a new mock instance.
func NewMockSystemSpecs(ctrl *gomock.Controller) *MockSystemSpecs {
	mock := &MockSystemSpecs{ctrl: ctrl}
	mock.recorder = &MockSystemSpecsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemSpecs) EXPECT() *MockSystemSpecsMockRecorder {
	return m.recorder
}

// GetMachineResources mocks base method.
func (m *MockSystemSpecs) GetMachineResources() (types.MachineResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineResources")
	ret0, _ := ret[0].(types.MachineResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineResources indicates an expected call of GetMachineResources.
func (mr *MockSystemSpecsMockRecorder) GetMachineResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineResources", reflect.TypeOf((*MockSystemSpecs)(nil).GetMachineResources))
}
