// Code generated by MockGen. DO NOT EDIT.
// Source: types/hardware.go
//
// Generated by this command:
//
//	mockgen -destination=dms/resources/mock_hardware_manager_test.go -source=types/hardware.go -package=resources
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockHardwareManager is a mock of HardwareManager interface.
type MockHardwareManager struct {
	ctrl     *gomock.Controller
	recorder *MockHardwareManagerMockRecorder
	isgomock struct{}
}

// MockHardwareManagerMockRecorder is the mock recorder for MockHardwareManager.
type MockHardwareManagerMockRecorder struct {
	mock *MockHardwareManager
}

// NewMockHardwareManager creates a new mock instance.
func NewMockHardwareManager(ctrl *gomock.Controller) *MockHardwareManager {
	mock := &MockHardwareManager{ctrl: ctrl}
	mock.recorder = &MockHardwareManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHardwareManager) EXPECT() *MockHardwareManagerMockRecorder {
	return m.recorder
}

// CheckCapacity mocks base method.
func (m *MockHardwareManager) CheckCapacity(resources types.Resources) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCapacity", resources)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCapacity indicates an expected call of CheckCapacity.
func (mr *MockHardwareManagerMockRecorder) CheckCapacity(resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCapacity", reflect.TypeOf((*MockHardwareManager)(nil).CheckCapacity), resources)
}

// GetFreeResources mocks base method.
func (m *MockHardwareManager) GetFreeResources() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeResources")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeResources indicates an expected call of GetFreeResources.
func (mr *MockHardwareManagerMockRecorder) GetFreeResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeResources", reflect.TypeOf((*MockHardwareManager)(nil).GetFreeResources))
}

// GetMachineResources mocks base method.
func (m *MockHardwareManager) GetMachineResources() (types.MachineResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineResources")
	ret0, _ := ret[0].(types.MachineResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineResources indicates an expected call of GetMachineResources.
func (mr *MockHardwareManagerMockRecorder) GetMachineResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineResources", reflect.TypeOf((*MockHardwareManager)(nil).GetMachineResources))
}

// GetUsage mocks base method.
func (m *MockHardwareManager) GetUsage() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockHardwareManagerMockRecorder) GetUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockHardwareManager)(nil).GetUsage))
}

// MockGPUManager is a mock of GPUManager interface.
type MockGPUManager struct {
	ctrl     *gomock.Controller
	recorder *MockGPUManagerMockRecorder
	isgomock struct{}
}

// MockGPUManagerMockRecorder is the mock recorder for MockGPUManager.
type MockGPUManagerMockRecorder struct {
	mock *MockGPUManager
}

// NewMockGPUManager creates a new mock instance.
func NewMockGPUManager(ctrl *gomock.Controller) *MockGPUManager {
	mock := &MockGPUManager{ctrl: ctrl}
	mock.recorder = &MockGPUManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUManager) EXPECT() *MockGPUManagerMockRecorder {
	return m.recorder
}

// GetGPUUsage mocks base method.
func (m *MockGPUManager) GetGPUUsage(uuid ...string) (types.GPUs, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range uuid {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGPUUsage", varargs...)
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUUsage indicates an expected call of GetGPUUsage.
func (mr *MockGPUManagerMockRecorder) GetGPUUsage(uuid ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUUsage", reflect.TypeOf((*MockGPUManager)(nil).GetGPUUsage), uuid...)
}

// GetGPUs mocks base method.
func (m *MockGPUManager) GetGPUs() (types.GPUs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUs")
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUs indicates an expected call of GetGPUs.
func (mr *MockGPUManagerMockRecorder) GetGPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUs", reflect.TypeOf((*MockGPUManager)(nil).GetGPUs))
}

// Shutdown mocks base method.
func (m *MockGPUManager) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGPUManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGPUManager)(nil).Shutdown))
}

// MockGPUConnector is a mock of GPUConnector interface.
type MockGPUConnector struct {
	ctrl     *gomock.Controller
	recorder *MockGPUConnectorMockRecorder
	isgomock struct{}
}

// MockGPUConnectorMockRecorder is the mock recorder for MockGPUConnector.
type MockGPUConnectorMockRecorder struct {
	mock *MockGPUConnector
}

// NewMockGPUConnector creates a new mock instance.
func NewMockGPUConnector(ctrl *gomock.Controller) *MockGPUConnector {
	mock := &MockGPUConnector{ctrl: ctrl}
	mock.recorder = &MockGPUConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUConnector) EXPECT() *MockGPUConnectorMockRecorder {
	return m.recorder
}

// GetGPUUsage mocks base method.
func (m *MockGPUConnector) GetGPUUsage(uuid string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUUsage", uuid)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUUsage indicates an expected call of GetGPUUsage.
func (mr *MockGPUConnectorMockRecorder) GetGPUUsage(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUUsage", reflect.TypeOf((*MockGPUConnector)(nil).GetGPUUsage), uuid)
}

// GetGPUs mocks base method.
func (m *MockGPUConnector) GetGPUs() (types.GPUs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUs")
	ret0, _ := ret[0].(types.GPUs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUs indicates an expected call of GetGPUs.
func (mr *MockGPUConnectorMockRecorder) GetGPUs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUs", reflect.TypeOf((*MockGPUConnector)(nil).GetGPUs))
}

// Shutdown mocks base method.
func (m *MockGPUConnector) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGPUConnectorMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGPUConnector)(nil).Shutdown))
}
