// Code generated by MockGen. DO NOT EDIT.
// Source: ../../types/resource.go
//
// Generated by this command:
//
//	mockgen -destination=mock_usage_monitor_test.go -source=../../types/resource.go -package=resources -exclude_interfaces=ResourceManager,ResourceOps
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageMonitor is a mock of UsageMonitor interface.
type MockUsageMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockUsageMonitorMockRecorder
}

// MockUsageMonitorMockRecorder is the mock recorder for MockUsageMonitor.
type MockUsageMonitorMockRecorder struct {
	mock *MockUsageMonitor
}

// NewMockUsageMonitor creates a new mock instance.
func NewMockUsageMonitor(ctrl *gomock.Controller) *MockUsageMonitor {
	mock := &MockUsageMonitor{ctrl: ctrl}
	mock.recorder = &MockUsageMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageMonitor) EXPECT() *MockUsageMonitorMockRecorder {
	return m.recorder
}

// GetUsage mocks base method.
func (m *MockUsageMonitor) GetUsage(arg0 context.Context) (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage", arg0)
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockUsageMonitorMockRecorder) GetUsage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockUsageMonitor)(nil).GetUsage), arg0)
}
