// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/nunet/device-management-service/dms/resources (interfaces: SystemSpecs)
//
// Generated by this command:
//
//	mockgen -destination=mock_system_specs_test.go -package=resources . SystemSpecs
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemSpecs is a mock of SystemSpecs interface.
type MockSystemSpecs struct {
	ctrl     *gomock.Controller
	recorder *MockSystemSpecsMockRecorder
}

// MockSystemSpecsMockRecorder is the mock recorder for MockSystemSpecs.
type MockSystemSpecsMockRecorder struct {
	mock *MockSystemSpecs
}

// NewMockSystemSpecs creates a new mock instance.
func NewMockSystemSpecs(ctrl *gomock.Controller) *MockSystemSpecs {
	mock := &MockSystemSpecs{ctrl: ctrl}
	mock.recorder = &MockSystemSpecsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemSpecs) EXPECT() *MockSystemSpecsMockRecorder {
	return m.recorder
}

// GetCPUInfo mocks base method.
func (m *MockSystemSpecs) GetCPUInfo() (types.CPUInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCPUInfo")
	ret0, _ := ret[0].(types.CPUInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCPUInfo indicates an expected call of GetCPUInfo.
func (mr *MockSystemSpecsMockRecorder) GetCPUInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCPUInfo", reflect.TypeOf((*MockSystemSpecs)(nil).GetCPUInfo))
}

// GetGPUVendors mocks base method.
func (m *MockSystemSpecs) GetGPUVendors() ([]types.GPUVendor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUVendors")
	ret0, _ := ret[0].([]types.GPUVendor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUVendors indicates an expected call of GetGPUVendors.
func (mr *MockSystemSpecsMockRecorder) GetGPUVendors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUVendors", reflect.TypeOf((*MockSystemSpecs)(nil).GetGPUVendors))
}

// GetGPUs mocks base method.
func (m *MockSystemSpecs) GetGPUs(arg0 ...types.GPUVendor) ([]types.GPU, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGPUs", varargs...)
	ret0, _ := ret[0].([]types.GPU)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUs indicates an expected call of GetGPUs.
func (mr *MockSystemSpecsMockRecorder) GetGPUs(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUs", reflect.TypeOf((*MockSystemSpecs)(nil).GetGPUs), arg0...)
}

// GetProvisionedResources mocks base method.
func (m *MockSystemSpecs) GetProvisionedResources() (types.Resources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvisionedResources")
	ret0, _ := ret[0].(types.Resources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvisionedResources indicates an expected call of GetProvisionedResources.
func (mr *MockSystemSpecsMockRecorder) GetProvisionedResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvisionedResources", reflect.TypeOf((*MockSystemSpecs)(nil).GetProvisionedResources))
}

// GetSpecInfo mocks base method.
func (m *MockSystemSpecs) GetSpecInfo() (types.SpecInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecInfo")
	ret0, _ := ret[0].(types.SpecInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecInfo indicates an expected call of GetSpecInfo.
func (mr *MockSystemSpecsMockRecorder) GetSpecInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecInfo", reflect.TypeOf((*MockSystemSpecs)(nil).GetSpecInfo))
}

// GetTotalMemory mocks base method.
func (m *MockSystemSpecs) GetTotalMemory() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalMemory")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalMemory indicates an expected call of GetTotalMemory.
func (mr *MockSystemSpecsMockRecorder) GetTotalMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalMemory", reflect.TypeOf((*MockSystemSpecs)(nil).GetTotalMemory))
}

// GetTotalStorage mocks base method.
func (m *MockSystemSpecs) GetTotalStorage() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalStorage")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalStorage indicates an expected call of GetTotalStorage.
func (mr *MockSystemSpecsMockRecorder) GetTotalStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalStorage", reflect.TypeOf((*MockSystemSpecs)(nil).GetTotalStorage))
}
