// Code generated by MockGen. DO NOT EDIT.
// Source: ../../db/repositories/generic_repository.go
//
// Generated by this command:
//
//	mockgen -source=../../db/repositories/generic_repository.go -destination mock_generic_repository_test.go -package=resources
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	repositories "gitlab.com/nunet/device-management-service/db/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockModelType is a mock of ModelType interface.
type MockModelType struct {
	ctrl     *gomock.Controller
	recorder *MockModelTypeMockRecorder
}

// MockModelTypeMockRecorder is the mock recorder for MockModelType.
type MockModelTypeMockRecorder struct {
	mock *MockModelType
}

// NewMockModelType creates a new mock instance.
func NewMockModelType(ctrl *gomock.Controller) *MockModelType {
	mock := &MockModelType{ctrl: ctrl}
	mock.recorder = &MockModelTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelType) EXPECT() *MockModelTypeMockRecorder {
	return m.recorder
}

// MockGenericRepository is a mock of GenericRepository interface.
type MockGenericRepository[T repositories.ModelType] struct {
	ctrl     *gomock.Controller
	recorder *MockGenericRepositoryMockRecorder[T]
}

// MockGenericRepositoryMockRecorder is the mock recorder for MockGenericRepository.
type MockGenericRepositoryMockRecorder[T repositories.ModelType] struct {
	mock *MockGenericRepository[T]
}

// NewMockGenericRepository creates a new mock instance.
func NewMockGenericRepository[T repositories.ModelType](ctrl *gomock.Controller) *MockGenericRepository[T] {
	mock := &MockGenericRepository[T]{ctrl: ctrl}
	mock.recorder = &MockGenericRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericRepository[T]) EXPECT() *MockGenericRepositoryMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockGenericRepository[T]) Create(ctx context.Context, data T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGenericRepositoryMockRecorder[T]) Create(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGenericRepository[T])(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockGenericRepository[T]) Delete(ctx context.Context, id any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGenericRepositoryMockRecorder[T]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGenericRepository[T])(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockGenericRepository[T]) Find(ctx context.Context, query repositories.Query[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, query)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGenericRepositoryMockRecorder[T]) Find(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGenericRepository[T])(nil).Find), ctx, query)
}

// FindAll mocks base method.
func (m *MockGenericRepository[T]) FindAll(ctx context.Context, query repositories.Query[T]) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, query)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGenericRepositoryMockRecorder[T]) FindAll(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGenericRepository[T])(nil).FindAll), ctx, query)
}

// Get mocks base method.
func (m *MockGenericRepository[T]) Get(ctx context.Context, id any) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGenericRepositoryMockRecorder[T]) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGenericRepository[T])(nil).Get), ctx, id)
}

// GetQuery mocks base method.
func (m *MockGenericRepository[T]) GetQuery() repositories.Query[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery")
	ret0, _ := ret[0].(repositories.Query[T])
	return ret0
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockGenericRepositoryMockRecorder[T]) GetQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockGenericRepository[T])(nil).GetQuery))
}

// Update mocks base method.
func (m *MockGenericRepository[T]) Update(ctx context.Context, id any, data T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGenericRepositoryMockRecorder[T]) Update(ctx, id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGenericRepository[T])(nil).Update), ctx, id, data)
}
