// Code generated by MockGen. DO NOT EDIT.
// Source: types/executor.go
//
// Generated by this command:
//
//	mockgen -destination=dms/node/mock_executor_test.go -source=types/executor.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockExecutor) Cancel(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockExecutorMockRecorder) Cancel(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockExecutor)(nil).Cancel), ctx, executionID)
}

// Cleanup mocks base method.
func (m *MockExecutor) Cleanup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockExecutorMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockExecutor)(nil).Cleanup), ctx)
}

// Exec mocks base method.
func (m *MockExecutor) Exec(ctx context.Context, containerID string, command []string) (int, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, containerID, command)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Exec indicates an expected call of Exec.
func (mr *MockExecutorMockRecorder) Exec(ctx, containerID, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockExecutor)(nil).Exec), ctx, containerID, command)
}

// GetID mocks base method.
func (m *MockExecutor) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockExecutorMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockExecutor)(nil).GetID))
}

// GetLogStream mocks base method.
func (m *MockExecutor) GetLogStream(ctx context.Context, request types.LogStreamRequest) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogStream", ctx, request)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogStream indicates an expected call of GetLogStream.
func (mr *MockExecutorMockRecorder) GetLogStream(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogStream", reflect.TypeOf((*MockExecutor)(nil).GetLogStream), ctx, request)
}

// GetStatus mocks base method.
func (m *MockExecutor) GetStatus(ctx context.Context, executionID string) (types.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, executionID)
	ret0, _ := ret[0].(types.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockExecutorMockRecorder) GetStatus(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockExecutor)(nil).GetStatus), ctx, executionID)
}

// List mocks base method.
func (m *MockExecutor) List() []types.ExecutionListItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]types.ExecutionListItem)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockExecutorMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExecutor)(nil).List))
}

// Pause mocks base method.
func (m *MockExecutor) Pause(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockExecutorMockRecorder) Pause(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockExecutor)(nil).Pause), ctx, executionID)
}

// Remove mocks base method.
func (m *MockExecutor) Remove(executionID string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", executionID, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockExecutorMockRecorder) Remove(executionID, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockExecutor)(nil).Remove), executionID, timeout)
}

// Resume mocks base method.
func (m *MockExecutor) Resume(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockExecutorMockRecorder) Resume(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockExecutor)(nil).Resume), ctx, executionID)
}

// Run mocks base method.
func (m *MockExecutor) Run(ctx context.Context, request *types.ExecutionRequest) (*types.ExecutionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, request)
	ret0, _ := ret[0].(*types.ExecutionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockExecutorMockRecorder) Run(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExecutor)(nil).Run), ctx, request)
}

// Start mocks base method.
func (m *MockExecutor) Start(ctx context.Context, request *types.ExecutionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockExecutorMockRecorder) Start(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockExecutor)(nil).Start), ctx, request)
}

// Wait mocks base method.
func (m *MockExecutor) Wait(ctx context.Context, executionID string) (<-chan *types.ExecutionResult, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx, executionID)
	ret0, _ := ret[0].(<-chan *types.ExecutionResult)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockExecutorMockRecorder) Wait(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockExecutor)(nil).Wait), ctx, executionID)
}

// WaitForStatus mocks base method.
func (m *MockExecutor) WaitForStatus(ctx context.Context, executionID string, status types.ExecutionStatus, timeout *time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForStatus", ctx, executionID, status, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForStatus indicates an expected call of WaitForStatus.
func (mr *MockExecutorMockRecorder) WaitForStatus(ctx, executionID, status, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForStatus", reflect.TypeOf((*MockExecutor)(nil).WaitForStatus), ctx, executionID, status, timeout)
}
