// Code generated by MockGen. DO NOT EDIT.
// Source: dms/orchestrator/orchestrator.go
//
// Generated by this command:
//
//	mockgen -destination=dms/node/mock_orchestrator_test.go -source=dms/orchestrator/orchestrator.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	reflect "reflect"
	time "time"

	crypto "github.com/libp2p/go-libp2p/core/crypto"
	jobtypes "gitlab.com/nunet/device-management-service/dms/jobs/types"
	orchestrator "gitlab.com/nunet/device-management-service/dms/orchestrator"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestrator is a mock of Orchestrator interface.
type MockOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorMockRecorder
}

// MockOrchestratorMockRecorder is the mock recorder for MockOrchestrator.
type MockOrchestratorMockRecorder struct {
	mock *MockOrchestrator
}

// NewMockOrchestrator creates a new mock instance.
func NewMockOrchestrator(ctrl *gomock.Controller) *MockOrchestrator {
	mock := &MockOrchestrator{ctrl: ctrl}
	mock.recorder = &MockOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrator) EXPECT() *MockOrchestratorMockRecorder {
	return m.recorder
}

// ActorPrivateKey mocks base method.
func (m *MockOrchestrator) ActorPrivateKey() crypto.PrivKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActorPrivateKey")
	ret0, _ := ret[0].(crypto.PrivKey)
	return ret0
}

// ActorPrivateKey indicates an expected call of ActorPrivateKey.
func (mr *MockOrchestratorMockRecorder) ActorPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActorPrivateKey", reflect.TypeOf((*MockOrchestrator)(nil).ActorPrivateKey))
}

// Config mocks base method.
func (m *MockOrchestrator) Config() jobtypes.EnsembleConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(jobtypes.EnsembleConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockOrchestratorMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockOrchestrator)(nil).Config))
}

// Deploy mocks base method.
func (m *MockOrchestrator) Deploy(expiry time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockOrchestratorMockRecorder) Deploy(expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockOrchestrator)(nil).Deploy), expiry)
}

// DeploymentSnapshot mocks base method.
func (m *MockOrchestrator) DeploymentSnapshot() jobtypes.DeploymentSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeploymentSnapshot")
	ret0, _ := ret[0].(jobtypes.DeploymentSnapshot)
	return ret0
}

// DeploymentSnapshot indicates an expected call of DeploymentSnapshot.
func (mr *MockOrchestratorMockRecorder) DeploymentSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeploymentSnapshot", reflect.TypeOf((*MockOrchestrator)(nil).DeploymentSnapshot))
}

// GetAllocationLogs mocks base method.
func (m *MockOrchestrator) GetAllocationLogs(name string) (orchestrator.AllocationLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocationLogs", name)
	ret0, _ := ret[0].(orchestrator.AllocationLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocationLogs indicates an expected call of GetAllocationLogs.
func (mr *MockOrchestratorMockRecorder) GetAllocationLogs(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocationLogs", reflect.TypeOf((*MockOrchestrator)(nil).GetAllocationLogs), name)
}

// ID mocks base method.
func (m *MockOrchestrator) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockOrchestratorMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockOrchestrator)(nil).ID))
}

// Manifest mocks base method.
func (m *MockOrchestrator) Manifest() jobtypes.EnsembleManifest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifest")
	ret0, _ := ret[0].(jobtypes.EnsembleManifest)
	return ret0
}

// Manifest indicates an expected call of Manifest.
func (mr *MockOrchestratorMockRecorder) Manifest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifest", reflect.TypeOf((*MockOrchestrator)(nil).Manifest))
}

// Shutdown mocks base method.
func (m *MockOrchestrator) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockOrchestratorMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockOrchestrator)(nil).Shutdown))
}

// Status mocks base method.
func (m *MockOrchestrator) Status() jobtypes.DeploymentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(jobtypes.DeploymentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockOrchestratorMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockOrchestrator)(nil).Status))
}

// Stop mocks base method.
func (m *MockOrchestrator) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockOrchestratorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockOrchestrator)(nil).Stop))
}

// WriteAllocationLogs mocks base method.
func (m *MockOrchestrator) WriteAllocationLogs(name string, stdout, stderr []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAllocationLogs", name, stdout, stderr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAllocationLogs indicates an expected call of WriteAllocationLogs.
func (mr *MockOrchestratorMockRecorder) WriteAllocationLogs(name, stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAllocationLogs", reflect.TypeOf((*MockOrchestrator)(nil).WriteAllocationLogs), name, stdout, stderr)
}
