// Code generated by MockGen. DO NOT EDIT.
// Source: dms/node/allocator.go
//
// Generated by this command:
//
//	mockgen -destination=dms/node/mock_allocator_test.go -source=dms/node/allocator.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	reflect "reflect"

	actor "gitlab.com/nunet/device-management-service/actor"
	jobs "gitlab.com/nunet/device-management-service/dms/jobs"
	jobtypes "gitlab.com/nunet/device-management-service/dms/jobs/types"
	types "gitlab.com/nunet/device-management-service/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAllocator is a mock of Allocator interface.
type MockAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockAllocatorMockRecorder
	isgomock struct{}
}

// MockAllocatorMockRecorder is the mock recorder for MockAllocator.
type MockAllocatorMockRecorder struct {
	mock *MockAllocator
}

// NewMockAllocator creates a new mock instance.
func NewMockAllocator(ctrl *gomock.Controller) *MockAllocator {
	mock := &MockAllocator{ctrl: ctrl}
	mock.recorder = &MockAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocator) EXPECT() *MockAllocatorMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockAllocator) Allocate(ctx context.Context, allocationID string, allocType jobtypes.AllocationType, actr actor.Actor, orchestrator actor.Handle, job jobs.Job, executor types.Executor) (*jobs.Allocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", ctx, allocationID, allocType, actr, orchestrator, job, executor)
	ret0, _ := ret[0].(*jobs.Allocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockAllocatorMockRecorder) Allocate(ctx, allocationID, allocType, actr, orchestrator, job, executor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockAllocator)(nil).Allocate), ctx, allocationID, allocType, actr, orchestrator, job, executor)
}

// CheckAvailability mocks base method.
func (m *MockAllocator) CheckAvailability(ports []int, numDynamicPorts int, resources types.Resources) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", ports, numDynamicPorts, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockAllocatorMockRecorder) CheckAvailability(ports, numDynamicPorts, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockAllocator)(nil).CheckAvailability), ports, numDynamicPorts, resources)
}

// Commit mocks base method.
func (m *MockAllocator) Commit(ctx context.Context, allocationID string, resources types.CommittedResources, ports map[int]int, numDynamicPorts int, expiry int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, allocationID, resources, ports, numDynamicPorts, expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockAllocatorMockRecorder) Commit(ctx, allocationID, resources, ports, numDynamicPorts, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockAllocator)(nil).Commit), ctx, allocationID, resources, ports, numDynamicPorts, expiry)
}

// GetAllocation mocks base method.
func (m *MockAllocator) GetAllocation(allocationID string) (*jobs.Allocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocation", allocationID)
	ret0, _ := ret[0].(*jobs.Allocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocation indicates an expected call of GetAllocation.
func (mr *MockAllocatorMockRecorder) GetAllocation(allocationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocation", reflect.TypeOf((*MockAllocator)(nil).GetAllocation), allocationID)
}

// GetAllocations mocks base method.
func (m *MockAllocator) GetAllocations() map[string]*jobs.Allocation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocations")
	ret0, _ := ret[0].(map[string]*jobs.Allocation)
	return ret0
}

// GetAllocations indicates an expected call of GetAllocations.
func (mr *MockAllocatorMockRecorder) GetAllocations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocations", reflect.TypeOf((*MockAllocator)(nil).GetAllocations))
}

// Release mocks base method.
func (m *MockAllocator) Release(ctx context.Context, allocationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, allocationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockAllocatorMockRecorder) Release(ctx, allocationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAllocator)(nil).Release), ctx, allocationID)
}

// Run mocks base method.
func (m *MockAllocator) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAllocatorMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAllocator)(nil).Run))
}

// Stop mocks base method.
func (m *MockAllocator) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAllocatorMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAllocator)(nil).Stop), ctx)
}

// Uncommit mocks base method.
func (m *MockAllocator) Uncommit(ctx context.Context, allocationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uncommit", ctx, allocationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Uncommit indicates an expected call of Uncommit.
func (mr *MockAllocatorMockRecorder) Uncommit(ctx, allocationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uncommit", reflect.TypeOf((*MockAllocator)(nil).Uncommit), ctx, allocationID)
}
