// Code generated by MockGen. DO NOT EDIT.
// Source: dms/orchestrator/registry.go
//
// Generated by this command:
//
//	mockgen -destination=dms/node/mock_orch_registry_test.go -source=dms/orchestrator/registry.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	reflect "reflect"

	afero "github.com/spf13/afero"
	actor "gitlab.com/nunet/device-management-service/actor"
	jobtypes "gitlab.com/nunet/device-management-service/dms/jobs/types"
	orchestrator "gitlab.com/nunet/device-management-service/dms/orchestrator"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// DeleteOrchestrator mocks base method.
func (m *MockRegistry) DeleteOrchestrator(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrchestrator", id)
}

// DeleteOrchestrator indicates an expected call of DeleteOrchestrator.
func (mr *MockRegistryMockRecorder) DeleteOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrchestrator", reflect.TypeOf((*MockRegistry)(nil).DeleteOrchestrator), id)
}

// GetOrchestrator mocks base method.
func (m *MockRegistry) GetOrchestrator(id string) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestrator", id)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrchestrator indicates an expected call of GetOrchestrator.
func (mr *MockRegistryMockRecorder) GetOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestrator", reflect.TypeOf((*MockRegistry)(nil).GetOrchestrator), id)
}

// NewOrchestrator mocks base method.
func (m *MockRegistry) NewOrchestrator(ctx context.Context, fs afero.Afero, workDir, id string, actor actor.Actor, cfg jobtypes.EnsembleConfig) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOrchestrator", ctx, fs, workDir, id, actor, cfg)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOrchestrator indicates an expected call of NewOrchestrator.
func (mr *MockRegistryMockRecorder) NewOrchestrator(ctx, fs, workDir, id, actor, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOrchestrator", reflect.TypeOf((*MockRegistry)(nil).NewOrchestrator), ctx, fs, workDir, id, actor, cfg)
}

// Orchestrators mocks base method.
func (m *MockRegistry) Orchestrators() map[string]orchestrator.Orchestrator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orchestrators")
	ret0, _ := ret[0].(map[string]orchestrator.Orchestrator)
	return ret0
}

// Orchestrators indicates an expected call of Orchestrators.
func (mr *MockRegistryMockRecorder) Orchestrators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orchestrators", reflect.TypeOf((*MockRegistry)(nil).Orchestrators))
}

// RestoreDeployment mocks base method.
func (m *MockRegistry) RestoreDeployment(actr actor.Actor, id string, cfg jobtypes.EnsembleConfig, manifest jobtypes.EnsembleManifest, status jobtypes.DeploymentStatus, restoreInfo jobtypes.DeploymentSnapshot) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeployment", actr, id, cfg, manifest, status, restoreInfo)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDeployment indicates an expected call of RestoreDeployment.
func (mr *MockRegistryMockRecorder) RestoreDeployment(actr, id, cfg, manifest, status, restoreInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeployment", reflect.TypeOf((*MockRegistry)(nil).RestoreDeployment), actr, id, cfg, manifest, status, restoreInfo)
}
