// Code generated by MockGen. DO NOT EDIT.
// Source: dms/orchestrator/provider.go
//
// Generated by this command:
//
//	mockgen -destination=dms/node/mock_orch_provider_test.go -source=dms/orchestrator/provider.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	reflect "reflect"

	afero "github.com/spf13/afero"
	actor "gitlab.com/nunet/device-management-service/actor"
	jobtypes "gitlab.com/nunet/device-management-service/dms/jobs/types"
	orchestrator "gitlab.com/nunet/device-management-service/dms/orchestrator"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestratorProvider is a mock of OrchestratorProvider interface.
type MockOrchestratorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorProviderMockRecorder
}

// MockOrchestratorProviderMockRecorder is the mock recorder for MockOrchestratorProvider.
type MockOrchestratorProviderMockRecorder struct {
	mock *MockOrchestratorProvider
}

// NewMockOrchestratorProvider creates a new mock instance.
func NewMockOrchestratorProvider(ctrl *gomock.Controller) *MockOrchestratorProvider {
	mock := &MockOrchestratorProvider{ctrl: ctrl}
	mock.recorder = &MockOrchestratorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestratorProvider) EXPECT() *MockOrchestratorProviderMockRecorder {
	return m.recorder
}

// DeleteOrchestrator mocks base method.
func (m *MockOrchestratorProvider) DeleteOrchestrator(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrchestrator", id)
}

// DeleteOrchestrator indicates an expected call of DeleteOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) DeleteOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).DeleteOrchestrator), id)
}

// GetOrchestrator mocks base method.
func (m *MockOrchestratorProvider) GetOrchestrator(id string) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestrator", id)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrchestrator indicates an expected call of GetOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) GetOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).GetOrchestrator), id)
}

// NewOrchestrator mocks base method.
func (m *MockOrchestratorProvider) NewOrchestrator(ctx context.Context, fs afero.Afero, workDir, id string, actor actor.Actor, cfg jobtypes.EnsembleConfig) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOrchestrator", ctx, fs, workDir, id, actor, cfg)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOrchestrator indicates an expected call of NewOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) NewOrchestrator(ctx, fs, workDir, id, actor, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).NewOrchestrator), ctx, fs, workDir, id, actor, cfg)
}

// Orchestrators mocks base method.
func (m *MockOrchestratorProvider) Orchestrators() map[string]orchestrator.Orchestrator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orchestrators")
	ret0, _ := ret[0].(map[string]orchestrator.Orchestrator)
	return ret0
}

// Orchestrators indicates an expected call of Orchestrators.
func (mr *MockOrchestratorProviderMockRecorder) Orchestrators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orchestrators", reflect.TypeOf((*MockOrchestratorProvider)(nil).Orchestrators))
}

// RestoreDeployment mocks base method.
func (m *MockOrchestratorProvider) RestoreDeployment(actr actor.Actor, id string, cfg jobtypes.EnsembleConfig, manifest jobtypes.EnsembleManifest, status jobtypes.DeploymentStatus, restoreInfo jobtypes.DeploymentSnapshot) (orchestrator.Orchestrator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeployment", actr, id, cfg, manifest, status, restoreInfo)
	ret0, _ := ret[0].(orchestrator.Orchestrator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDeployment indicates an expected call of RestoreDeployment.
func (mr *MockOrchestratorProviderMockRecorder) RestoreDeployment(actr, id, cfg, manifest, status, restoreInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeployment", reflect.TypeOf((*MockOrchestratorProvider)(nil).RestoreDeployment), actr, id, cfg, manifest, status, restoreInfo)
}
