// Code generated by MockGen. DO NOT EDIT.
// Source: ../jobs/orchestrator.go
//
// Generated by this command:
//
//	mockgen -destination=mock_orchestrator_test.go -source=../jobs/orchestrator.go -package=node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	reflect "reflect"
	time "time"

	crypto "github.com/libp2p/go-libp2p/core/crypto"
	actor "gitlab.com/nunet/device-management-service/actor"
	jobs "gitlab.com/nunet/device-management-service/dms/jobs"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestratorProvider is a mock of OrchestratorProvider interface.
type MockOrchestratorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorProviderMockRecorder
}

// MockOrchestratorProviderMockRecorder is the mock recorder for MockOrchestratorProvider.
type MockOrchestratorProviderMockRecorder struct {
	mock *MockOrchestratorProvider
}

// NewMockOrchestratorProvider creates a new mock instance.
func NewMockOrchestratorProvider(ctrl *gomock.Controller) *MockOrchestratorProvider {
	mock := &MockOrchestratorProvider{ctrl: ctrl}
	mock.recorder = &MockOrchestratorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestratorProvider) EXPECT() *MockOrchestratorProviderMockRecorder {
	return m.recorder
}

// DeleteOrchestrator mocks base method.
func (m *MockOrchestratorProvider) DeleteOrchestrator(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrchestrator", id)
}

// DeleteOrchestrator indicates an expected call of DeleteOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) DeleteOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).DeleteOrchestrator), id)
}

// GetOrchestrator mocks base method.
func (m *MockOrchestratorProvider) GetOrchestrator(id string) (jobs.OrchestratorAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestrator", id)
	ret0, _ := ret[0].(jobs.OrchestratorAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrchestrator indicates an expected call of GetOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) GetOrchestrator(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).GetOrchestrator), id)
}

// NewOrchestrator mocks base method.
func (m *MockOrchestratorProvider) NewOrchestrator(ctx context.Context, id string, actor actor.Actor, cfg jobs.EnsembleConfig) (jobs.OrchestratorAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOrchestrator", ctx, id, actor, cfg)
	ret0, _ := ret[0].(jobs.OrchestratorAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOrchestrator indicates an expected call of NewOrchestrator.
func (mr *MockOrchestratorProviderMockRecorder) NewOrchestrator(ctx, id, actor, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOrchestrator", reflect.TypeOf((*MockOrchestratorProvider)(nil).NewOrchestrator), ctx, id, actor, cfg)
}

// Orchestrators mocks base method.
func (m *MockOrchestratorProvider) Orchestrators() map[string]jobs.OrchestratorAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orchestrators")
	ret0, _ := ret[0].(map[string]jobs.OrchestratorAPI)
	return ret0
}

// Orchestrators indicates an expected call of Orchestrators.
func (mr *MockOrchestratorProviderMockRecorder) Orchestrators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orchestrators", reflect.TypeOf((*MockOrchestratorProvider)(nil).Orchestrators))
}

// RestoreDeployment mocks base method.
func (m *MockOrchestratorProvider) RestoreDeployment(actr actor.Actor, id string, cfg jobs.EnsembleConfig, manifest jobs.EnsembleManifest, status jobs.DeploymentStatus, restoreInfo jobs.DeploymentSnapshot) (jobs.OrchestratorAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeployment", actr, id, cfg, manifest, status, restoreInfo)
	ret0, _ := ret[0].(jobs.OrchestratorAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDeployment indicates an expected call of RestoreDeployment.
func (mr *MockOrchestratorProviderMockRecorder) RestoreDeployment(actr, id, cfg, manifest, status, restoreInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeployment", reflect.TypeOf((*MockOrchestratorProvider)(nil).RestoreDeployment), actr, id, cfg, manifest, status, restoreInfo)
}

// MockOrchestratorAPI is a mock of OrchestratorAPI interface.
type MockOrchestratorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorAPIMockRecorder
}

// MockOrchestratorAPIMockRecorder is the mock recorder for MockOrchestratorAPI.
type MockOrchestratorAPIMockRecorder struct {
	mock *MockOrchestratorAPI
}

// NewMockOrchestratorAPI creates a new mock instance.
func NewMockOrchestratorAPI(ctrl *gomock.Controller) *MockOrchestratorAPI {
	mock := &MockOrchestratorAPI{ctrl: ctrl}
	mock.recorder = &MockOrchestratorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestratorAPI) EXPECT() *MockOrchestratorAPIMockRecorder {
	return m.recorder
}

// ActorPrivateKey mocks base method.
func (m *MockOrchestratorAPI) ActorPrivateKey() crypto.PrivKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActorPrivateKey")
	ret0, _ := ret[0].(crypto.PrivKey)
	return ret0
}

// ActorPrivateKey indicates an expected call of ActorPrivateKey.
func (mr *MockOrchestratorAPIMockRecorder) ActorPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActorPrivateKey", reflect.TypeOf((*MockOrchestratorAPI)(nil).ActorPrivateKey))
}

// Config mocks base method.
func (m *MockOrchestratorAPI) Config() jobs.EnsembleConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(jobs.EnsembleConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockOrchestratorAPIMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockOrchestratorAPI)(nil).Config))
}

// Deploy mocks base method.
func (m *MockOrchestratorAPI) Deploy(expiry time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", expiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockOrchestratorAPIMockRecorder) Deploy(expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockOrchestratorAPI)(nil).Deploy), expiry)
}

// DeploymentSnapshot mocks base method.
func (m *MockOrchestratorAPI) DeploymentSnapshot() jobs.DeploymentSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeploymentSnapshot")
	ret0, _ := ret[0].(jobs.DeploymentSnapshot)
	return ret0
}

// DeploymentSnapshot indicates an expected call of DeploymentSnapshot.
func (mr *MockOrchestratorAPIMockRecorder) DeploymentSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeploymentSnapshot", reflect.TypeOf((*MockOrchestratorAPI)(nil).DeploymentSnapshot))
}

// GetAllocationLogs mocks base method.
func (m *MockOrchestratorAPI) GetAllocationLogs(name string) (jobs.AllocationLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocationLogs", name)
	ret0, _ := ret[0].(jobs.AllocationLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocationLogs indicates an expected call of GetAllocationLogs.
func (mr *MockOrchestratorAPIMockRecorder) GetAllocationLogs(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocationLogs", reflect.TypeOf((*MockOrchestratorAPI)(nil).GetAllocationLogs), name)
}

// ID mocks base method.
func (m *MockOrchestratorAPI) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockOrchestratorAPIMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockOrchestratorAPI)(nil).ID))
}

// Manifest mocks base method.
func (m *MockOrchestratorAPI) Manifest() jobs.EnsembleManifest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifest")
	ret0, _ := ret[0].(jobs.EnsembleManifest)
	return ret0
}

// Manifest indicates an expected call of Manifest.
func (mr *MockOrchestratorAPIMockRecorder) Manifest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifest", reflect.TypeOf((*MockOrchestratorAPI)(nil).Manifest))
}

// Shutdown mocks base method.
func (m *MockOrchestratorAPI) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockOrchestratorAPIMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockOrchestratorAPI)(nil).Shutdown))
}

// Status mocks base method.
func (m *MockOrchestratorAPI) Status() jobs.DeploymentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(jobs.DeploymentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockOrchestratorAPIMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockOrchestratorAPI)(nil).Status))
}

// Stop mocks base method.
func (m *MockOrchestratorAPI) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockOrchestratorAPIMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockOrchestratorAPI)(nil).Stop))
}
