// Copyright 2024, Nunet
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package node

import (
	"fmt"
	"time"

	"github.com/google/uuid"
	"gitlab.com/nunet/device-management-service/actor"
	"gitlab.com/nunet/device-management-service/dms/behaviors"
	"gitlab.com/nunet/device-management-service/network"
	"gitlab.com/nunet/device-management-service/tokenomics/contracts"
	"gitlab.com/nunet/device-management-service/tokenomics/store/payment"
	"gitlab.com/nunet/device-management-service/types"
)

const NTXCurrency = "NTX"

// PaymentProcessor defines the interface for processing payment items.
// This interface allows for different implementations and easy testing.
type PaymentProcessor interface {
	// ProcessPaymentItems processes a batch of payment items for a contract.
	// This method:
	// - Generates unique IDs for items that don't have one
	// - Saves each payment to the payment store
	// - Forwards transaction requests to the service provider
	// - Continues processing even if individual items fail
	// Returns an error only if there's a critical failure that prevents processing.
	ProcessPaymentItems(
		contract *contracts.Contract,
		items []*contracts.PaymentItem,
		baseUniqueID string,
	) error
}

// paymentProcessorImpl implements PaymentProcessor
type paymentProcessorImpl struct {
	paymentStore    *payment.Store
	network         network.Network
	actor           actor.Handle
	invokeBehaviour func(destination actor.Handle, behavior string, req interface{}, timeout time.Duration) (actor.Envelope, error)
}

// NewPaymentProcessor creates a new payment processor implementation
func NewPaymentProcessor(
	paymentStore *payment.Store,
	network network.Network,
	actor actor.Handle,
	invokeBehaviour func(destination actor.Handle, behavior string, req interface{}, timeout time.Duration) (actor.Envelope, error),
) PaymentProcessor {
	if paymentStore == nil {
		panic("payment store cannot be nil")
	}
	if network == nil {
		panic("network cannot be nil")
	}
	if actor.ID.String() == "" {
		panic("actor handle cannot be empty")
	}
	if invokeBehaviour == nil {
		panic("invokeBehaviour function cannot be nil")
	}

	return &paymentProcessorImpl{
		paymentStore:    paymentStore,
		network:         network,
		actor:           actor,
		invokeBehaviour: invokeBehaviour,
	}
}

// ProcessPaymentItems implements PaymentProcessor.ProcessPaymentItems
func (pp *paymentProcessorImpl) ProcessPaymentItems(
	contract *contracts.Contract,
	items []*contracts.PaymentItem,
	_ string, // baseUniqueID - no longer used, UUIDs generated in payment processors
) error {
	if contract == nil {
		return fmt.Errorf("contract cannot be nil")
	}
	if len(items) == 0 {
		return nil // No items to process
	}

	// Process each item
	for _, item := range items {
		// UUID should already be generated by payment processor in CalculatePayment
		// If not set, log a warning (should not happen in normal flow)
		if item.UniqueID == "" {
			log.Warnf("PaymentItem has empty UniqueID, this should not happen")
			// Fallback: generate UUID if somehow missing (defensive programming)
			item.UniqueID = uuid.NewString()
		}

		// Build transaction metadata from PaymentItem
		// Start with a copy of PaymentItem.Metadata (if it exists)
		metadata := make(map[string]interface{})
		if item.Metadata != nil {
			// Copy all existing metadata
			for k, v := range item.Metadata {
				metadata[k] = v
			}
		}

		// Add deployment_id from PaymentItem.DeploymentID
		if item.DeploymentID != "" {
			metadata["deployment_id"] = item.DeploymentID
		}

		// Store metadata back in PaymentItem for use in forwardTransaction
		item.Metadata = metadata

		// Save payment
		if err := pp.savePayment(contract, item); err != nil {
			log.Errorf("failed to save payment for item %s: %v", item.UniqueID, err)
			continue // Continue with other items
		}

		// Forward transaction
		if err := pp.forwardTransaction(contract, item); err != nil {
			log.Errorf("failed to forward transaction for item %s: %v", item.UniqueID, err)
			// Continue - payment is saved
		}
	}

	// Calculate and process orchestration fee for the entire batch
	if contract.PaymentDetails.OrchestrationFee == nil {
		return nil // No orchestration fee configured
	}

	feeCalculator := contracts.NewOrchestrationFeeCalculator()

	// Calculate fee based on all payment items
	feeAmount, err := feeCalculator.CalculateFee(items, contract.PaymentDetails.OrchestrationFee)
	if err != nil {
		log.Errorf("failed to calculate orchestration fee: %v", err)
		return nil // Don't fail - primary transactions already processed
	}

	if feeAmount == "" {
		return nil // No fee to generate
	}

	// Generate orchestration fee item
	feeItem, err := feeCalculator.GenerateOrchestrationFeeItem(
		items,
		contract,
		items[0].UniqueID,
		feeAmount,
	)
	if err != nil {
		log.Errorf("failed to generate orchestration fee item: %v", err)
		return nil // Don't fail - primary transactions already processed
	}

	if feeItem == nil {
		return nil // No fee item generated
	}

	// Process orchestration fee item using existing methods.
	// Save payment with addresses set so the payment validator can verify: it fetches ERC20/Cardano
	// transfers to ProviderAddr and checks From == RequesterAddr. For orchestration fee the transfer
	// is requestor -> orchestration recipient, so we must store RequesterAddr = payer, ProviderAddr = recipient.
	var contractForSave *contracts.Contract
	if contract.PaymentDetails.OrchestrationFee.RecipientAddress.RequesterAddr != "" ||
		contract.PaymentDetails.OrchestrationFee.RecipientAddress.ProviderAddr != "" {
		recipient := contract.PaymentDetails.OrchestrationFee.RecipientAddress
		orchestrationRecipientAddr := recipient.ProviderAddr
		if orchestrationRecipientAddr == "" {
			orchestrationRecipientAddr = recipient.RequesterAddr
		}
		// Use contract requestor as payer; orchestration recipient as "provider" for validation (transfers TO this address).
		var payerAddr string
		for _, a := range contract.PaymentDetails.Addresses {
			if a.Blockchain == recipient.Blockchain {
				payerAddr = a.RequesterAddr
				break
			}
		}
		addrForValidation := types.PaymentAddressInfo{
			Blockchain:    recipient.Blockchain,
			Currency:      recipient.Currency,
			RequesterAddr: payerAddr,
			ProviderAddr:  orchestrationRecipientAddr,
		}
		copyForSave := *contract
		copyForSave.PaymentDetails.Addresses = []types.PaymentAddressInfo{addrForValidation}
		contractForSave = &copyForSave
	} else {
		contractForSave = contract
	}
	if err := pp.savePayment(contractForSave, feeItem); err != nil {
		log.Errorf("failed to save orchestration fee payment: %v", err)
		return nil // Don't fail - primary transactions already processed
	}

	// Forward transaction - create temporary contract copy with modified addresses if needed
	tempContract := *contract
	if contract.PaymentDetails.OrchestrationFee.RecipientAddress.RequesterAddr != "" ||
		contract.PaymentDetails.OrchestrationFee.RecipientAddress.ProviderAddr != "" {
		tempContract.PaymentDetails.Addresses = []types.PaymentAddressInfo{
			contract.PaymentDetails.OrchestrationFee.RecipientAddress,
		}
	}

	// Forward transaction using existing forwardTransaction method
	// This forwards to the original requestor (same as primary transactions)
	if err := pp.forwardTransaction(&tempContract, feeItem); err != nil {
		log.Errorf("failed to forward orchestration fee transaction: %v", err)
		// Continue - payment is saved
	}

	return nil
}

// savePayment saves a payment to the payment store
func (pp *paymentProcessorImpl) savePayment(contract *contracts.Contract, item *contracts.PaymentItem) error {
	paymnt := payment.Payment{
		UniqueID: item.UniqueID,
		Contract: *contract,
		Usages:   item.Usages,
		Amount:   item.Amount,
		Paid:     false,

		ToAddress: contract.PaymentDetails.Addresses,
	}

	// If pricing_currency is set, store original amount and conversion metadata
	// NO CONVERSION HAPPENS HERE - conversion only happens at quote time
	if contract.PaymentDetails.PricingCurrency != "" &&
		contract.PaymentDetails.PricingCurrency != NTXCurrency {
		// Store original amount in pricing currency (e.g., USDT)
		// The Amount field contains the original amount in pricing currency
		// Conversion to NTX will happen later when user requests a quote
		paymnt.OriginalAmount = item.Amount
		paymnt.PricingCurrency = contract.PaymentDetails.PricingCurrency
		paymnt.RequiresConversion = true
	}

	return pp.paymentStore.Insert(paymnt)
}

// forwardTransaction forwards a transaction request to the service provider
func (pp *paymentProcessorImpl) forwardTransaction(
	contract *contracts.Contract,
	item *contracts.PaymentItem,
) error {
	// Create transaction request
	txReq := contracts.TransactionForServiceProviderRequest{
		PaymentValidatorDID: contract.PaymentValidatorDID.URI,
		UniqueID:            item.UniqueID,
		ContractDID:         contract.ContractDID,
		ToAddress:           contract.PaymentDetails.Addresses,
		Amount:              item.Amount, // Store original amount (in pricing currency if conversion needed)
		Status:              "unpaid",
		Metadata:            item.Metadata,
	}

	// If pricing_currency is set, store original amount and conversion metadata
	// NO CONVERSION HAPPENS HERE - conversion only happens at quote time
	if contract.PaymentDetails.PricingCurrency != "" &&
		contract.PaymentDetails.PricingCurrency != NTXCurrency {
		// Store original amount in pricing currency (e.g., USDT)
		// The Amount field contains the original amount in pricing currency
		// Conversion to NTX will happen later when user requests a quote
		txReq.OriginalAmount = item.Amount
		txReq.PricingCurrency = contract.PaymentDetails.PricingCurrency
		txReq.RequiresConversion = true
	}

	destination, err := actor.HandleFromDID(contract.ContractParticipants.Requestor.URI)
	if err != nil {
		return fmt.Errorf("failed to get requestor handle: %w", err)
	}

	go func() {
		reply, err := pp.invokeBehaviour(destination, behaviors.ContractTransactionBehavior, txReq, invokeMessageTimeout)
		if reply.Message == nil || err != nil {
			log.Errorf("failed to forward transaction %s: %v", item.UniqueID, err)
		}
	}()

	return nil
}
